// Builds src/words.js: 2048 short words (4–6 letters) from the EFF large wordlist (CC BY 3.0 US, Electronic Frontier
// Foundation, https://www.eff.org/dice). 2048 words = 11 bits each, so a 5-word passphrase is ~55 bits.
import { createRequire } from 'module';
import { writeFileSync } from 'fs';
const require = createRequire(import.meta.url);
const all = Object.values(require('diceware-wordlist-en-eff'));
const w = all.filter(x => /^[a-z]{4,6}$/.test(x)).slice(0, 2048);
if (w.length !== 2048 || new Set(w).size !== 2048) throw new Error('need 2048 unique words, got ' + w.length);
writeFileSync(new URL('../src/words.js', import.meta.url),
  '/* 2048 words (4–6 letters) from the EFF large wordlist — CC BY 3.0 US, Electronic Frontier Foundation (eff.org/dice). Generated by tools/words.mjs. */\n' +
  'export const WORDS = ' + JSON.stringify(w.join(' ')) + '.split(\' \');\n');
console.log('wrote', w.length, 'words');
