const { chromium } = require('playwright');
const { routes, watch } = require('./helpers');
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' }).catch(() => chromium.launch());
  const errs = [];
  const ctx = await browser.newContext({ viewport: { width: 1360, height: 900 } });
  await routes(ctx);
  const page = await ctx.newPage(); watch(page, errs, 'demo');
  await page.goto('http://127.0.0.1:8765/nlo-cases.html?demo');
  await page.click('#lgBtn');
  await page.waitForSelector('.tiles');
  await page.screenshot({ path: 'shots/today.png' });
  await page.click('#nav-board'); await page.waitForSelector('.board');
  await page.screenshot({ path: 'shots/board.png' });
  await page.click('[data-act=flow][data-k=inhouse]'); await page.screenshot({ path: 'shots/board-inhouse.png' });
  await page.click('#nav-list'); await page.waitForSelector('table.tbl');
  await page.screenshot({ path: 'shots/list.png' });
  await page.click('tr.click >> nth=0'); await page.waitForSelector('#drawer .stepper');
  await page.waitForTimeout(200);
  await page.screenshot({ path: 'shots/drawer.png' });
  await page.click('[data-act=closeDrawer] >> nth=0');
  await page.click('.topBar [data-act=newCase]'); await page.waitForSelector('#ncForm');
  await page.click('#ncForm .tt[data-tile=oliv]'); await page.fill('#cf-patient', 'Test Person');
  await page.screenshot({ path: 'shots/newcase.png' });
  console.log('auto dates', await page.inputValue('#cf-scanDate'), await page.inputValue('#cf-dueDate'), await page.inputValue('#cf-labDate'), await page.inputValue('#cf-deliveryDate'), 'assignee', await page.inputValue('#cf-assignee'));
  await page.click('#ncSave'); await page.waitForTimeout(300);
  await page.click('#nav-admin'); await page.waitForSelector('.adminGrid'); await page.screenshot({ path: 'shots/admin.png', fullPage: true });
  await page.click('#nav-import'); await page.screenshot({ path: 'shots/import.png' });
  await page.click('#nav-done'); await page.waitForTimeout(200); await page.screenshot({ path: 'shots/done.png' });
  // phone
  const m = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  await routes(m); const mp = await m.newPage(); watch(mp, errs, 'mobile');
  await mp.goto('http://127.0.0.1:8765/nlo-cases.html?demo'); await mp.click('#lgBtn'); await mp.waitForSelector('.tiles');
  await mp.screenshot({ path: 'shots/m-today.png' });
  await mp.click('#mnav-board'); await mp.screenshot({ path: 'shots/m-board.png' });
  await mp.click('.kc >> nth=0'); await mp.waitForSelector('#drawer'); await mp.screenshot({ path: 'shots/m-drawer.png' });
  console.log('ERRORS:', errs.length ? errs.join('\n') : 'none');
  await browser.close();
})().catch(e => { console.error('FAILED', e); process.exit(1); });
