// Security-rules tests: every request the app should allow, and the ones an attacker would try.
import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc, collection, writeBatch, serverTimestamp, Timestamp, deleteField, arrayUnion, query, where } from 'firebase/firestore';
import { readFileSync } from 'fs';

let pass = 0, fail = 0;
async function t(name, p, expectOk) {
  try { await (expectOk ? assertSucceeds(p) : assertFails(p)); pass++; console.log('  ok  ' + name); }
  catch (e) { fail++; console.log('  FAIL ' + name + ' :: ' + (e && e.message ? e.message.split('\n')[0] : e)); }
}
const ok = (n, p) => t(n, p, true), no = (n, p) => t(n, p, false);

const env = await initializeTestEnvironment({ projectId: 'demo-nlo-cases', firestore: { rules: readFileSync('dist/firestore.rules', 'utf8'), host: '127.0.0.1', port: 8080 } });
const box = { iv: 'aXY=', ct: 'Y3Q=' };
async function seed() {
  await env.clearFirestore();
  await env.withSecurityRulesDisabled(async c => {
    const db = c.firestore();
    await setDoc(doc(db, 'meta/setup'), { owner: 'owner', at: Timestamp.now() });
    await setDoc(doc(db, 'meta/keys'), { current: 2 });
    await setDoc(doc(db, 'meta/settings'), { idleMin: 10 });
    await setDoc(doc(db, 'meta/recovery'), { pub: {}, priv: box, ring: box, ringV: 2 });
    await setDoc(doc(db, 'members/owner'), { staffId: 'amir', role: 'owner', active: true, name: 'Owner' });
    await setDoc(doc(db, 'members/gwen'), { staffId: 'gwen', role: 'staff', active: true, name: 'Gwen', username: 'gwen', mustSetup: false, pub: {}, priv: box, ring: box, ringV: 2 });
    await setDoc(doc(db, 'members/kay'), { staffId: 'kaylee', role: 'staff', active: false, name: 'Kaylee', username: 'kaylee' });
    await setDoc(doc(db, 'roster/gwen'), { name: 'Gwen', active: true });
    await setDoc(doc(db, 'logins/gwen'), { email: 'gwen.1@staff.example' });
    await setDoc(doc(db, 'cases/c1'), { v: 2, ...box, status: 'open', rev: 3, by: 'owner', sid: 'amir', createdAt: Timestamp.fromMillis(1e12), updatedAt: Timestamp.now(), closedAt: null });
    await setDoc(doc(db, 'log/c1_3'), { caseId: 'c1', rev: 3, uid: 'owner', sid: 'amir', at: Timestamp.now(), v: 2, ...box, prev: { v: 2, iv: 'b2xk', ct: 'b2xk' } });
  });
}
const PREV = { v: 2, ...box };
const histDoc = (uid, sid, caseId, rev, prev, extra) => Object.assign({ caseId, rev, uid, sid, at: serverTimestamp(), v: 2, ...box, prev }, extra || {});
// write a case + its history entry in one batch, the way the app does
function caseWrite(db, id, data, hist, mode) {
  const b = writeBatch(db);
  if (mode === 'create') b.set(doc(db, 'cases/' + id), data); else if (mode === 'delete') b.delete(doc(db, 'cases/' + id)); else b.update(doc(db, 'cases/' + id), data);
  if (hist) b.set(doc(db, 'log/' + hist.caseId + '_' + hist.rev), hist);
  return b.commit();
}
const caseUpd = (uid, sid, extra) => Object.assign({ v: 2, ...box, status: 'open', rev: 4, by: uid, sid, createdAt: Timestamp.fromMillis(1e12), updatedAt: serverTimestamp(), closedAt: null }, extra || {});

await seed();
console.log('\n# Signed-out visitor');
let db = env.unauthenticatedContext().firestore();
await no('cannot read a case', getDoc(doc(db, 'cases/c1')));
await no('cannot list cases', getDocs(collection(db, 'cases')));
await no('cannot read members', getDoc(doc(db, 'members/gwen')));
await no('cannot read roster', getDocs(collection(db, 'roster')));
await no('cannot read the key version', getDoc(doc(db, 'meta/keys')));
await no('cannot read the history log', getDocs(collection(db, 'log')));
await ok('can look up one username (needed to sign in)', getDoc(doc(db, 'logins/gwen')));
await no('cannot list usernames', getDocs(collection(db, 'logins')));
await no('cannot write a case', caseWrite(db, 'x', caseUpd('anon', 'x', { rev: 1, createdAt: serverTimestamp() }), histDoc('anon', 'x', 'x', 1, null), 'create'));

console.log('\n# Stranger with an account (not a member)');
db = env.authenticatedContext('stranger').firestore();
await no('cannot read cases', getDocs(collection(db, 'cases')));
await no('cannot read roster', getDocs(collection(db, 'roster')));
await no('cannot read history', getDoc(doc(db, 'log/c1_3')));
await no('cannot make themself owner', setDoc(doc(db, 'members/stranger'), { staffId: 'x', role: 'owner', active: true }));
await no('cannot make themself staff', setDoc(doc(db, 'members/stranger'), { staffId: 'x', role: 'staff', active: true }));
await no('cannot overwrite the office setup', setDoc(doc(db, 'meta/setup'), { owner: 'stranger', at: serverTimestamp() }));
await no('cannot point a username at their account', setDoc(doc(db, 'logins/gwen'), { email: 'evil@example.com' }));
await no('cannot read the recovery record', getDoc(doc(db, 'meta/recovery')));
await no('cannot read who the owner is', getDoc(doc(db, 'meta/setup')));

console.log('\n# Removed staff member (inactive)');
db = env.authenticatedContext('kay').firestore();
await no('cannot read cases', getDocs(collection(db, 'cases')));
await no('cannot read history', getDocs(collection(db, 'log')));
await no('cannot write a case', caseWrite(db, 'c1', caseUpd('kay', 'kaylee'), histDoc('kay', 'kaylee', 'c1', 4, PREV)));
await no('cannot reactivate themself', updateDoc(doc(db, 'members/kay'), { active: true }));
await no('cannot even update their own key fields', updateDoc(doc(db, 'members/kay'), { lastLogin: serverTimestamp() }));

console.log('\n# Active staff (Gwen)');
db = env.authenticatedContext('gwen').firestore();
await ok('reads cases', getDocs(query(collection(db, 'cases'), where('status', '==', 'open'))));
await ok('reads history', getDocs(query(collection(db, 'log'), where('caseId', '==', 'c1'))));
await ok('reads roster', getDocs(collection(db, 'roster')));
await ok('reads key version', getDoc(doc(db, 'meta/keys')));
await ok('reads own member record', getDoc(doc(db, 'members/gwen')));
await no('cannot read someone else’s member record', getDoc(doc(db, 'members/owner')));
await no('cannot list member records', getDocs(collection(db, 'members')));
await no('cannot read the recovery record', getDoc(doc(db, 'meta/recovery')));
await ok('updates own key material', updateDoc(doc(db, 'members/gwen'), { ringV: 2, lastLogin: serverTimestamp(), privPrev: deleteField() }));
await no('cannot make themself owner', updateDoc(doc(db, 'members/gwen'), { role: 'owner' }));
await no('cannot rename their staff id', updateDoc(doc(db, 'members/gwen'), { staffId: 'amir' }));
await no('cannot create another login', setDoc(doc(db, 'members/newbie'), { staffId: 'n', role: 'staff', active: true }));
await no('cannot reactivate a removed person', updateDoc(doc(db, 'members/kay'), { active: true }));
await no('cannot edit the roster', setDoc(doc(db, 'roster/evil'), { name: 'x', active: true }));
await no('cannot change usernames', setDoc(doc(db, 'logins/gwen'), { email: 'x@example.com' }));
await no('cannot change the key version', updateDoc(doc(db, 'meta/keys'), { current: 3 }));
await no('cannot change settings', updateDoc(doc(db, 'meta/settings'), { idleMin: 600 }));
await ok('reads who the owner is', getDoc(doc(db, 'meta/setup')));
await ok('sets a valid public key', updateDoc(doc(db, 'members/gwen'), { pub: { kty: 'EC', crv: 'P-256', x: 'A'.repeat(43), y: 'B'.repeat(43) } }));
await no('cannot store a malformed public key', updateDoc(doc(db, 'members/gwen'), { pub: { kty: 'EC', crv: 'P-256', x: 'AAAA', y: 'AAAA' } }));
await no('cannot store a public key with extra fields', updateDoc(doc(db, 'members/gwen'), { pub: { kty: 'EC', crv: 'P-256', x: 'A'.repeat(43), y: 'B'.repeat(43), d: 'secret' } }));
await no('cannot update a case without a history entry', updateDoc(doc(db, 'cases/c1'), caseUpd('gwen', 'gwen')));
await no('history entry must hold the real previous copy', caseWrite(db, 'c1', caseUpd('gwen', 'gwen'), histDoc('gwen', 'gwen', 'c1', 4, { v: 2, iv: 'eA==', ct: 'eA==' })));
await no('history entry must hold a previous copy at all', caseWrite(db, 'c1', caseUpd('gwen', 'gwen'), histDoc('gwen', 'gwen', 'c1', 4, null)));
await no('cannot roll the revision back', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { rev: 2 }), histDoc('gwen', 'gwen', 'c1', 2, PREV)));
await no('cannot skip a revision', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { rev: 9 }), histDoc('gwen', 'gwen', 'c1', 9, PREV)));
await no('cannot add a history entry without changing the case', setDoc(doc(db, 'log/c1_4'), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot write with the old key version', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { v: 1 }), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot write as someone else (by)', caseWrite(db, 'c1', caseUpd('owner', 'gwen'), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot write as someone else (sid)', caseWrite(db, 'c1', caseUpd('gwen', 'amir'), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot sign history as someone else', caseWrite(db, 'c1', caseUpd('gwen', 'gwen'), histDoc('owner', 'amir', 'c1', 4, PREV)));
await no('cannot add plaintext fields to a case', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { patient: 'Leak Example' }), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot add plaintext fields to history', caseWrite(db, 'c1', caseUpd('gwen', 'gwen'), histDoc('gwen', 'gwen', 'c1', 4, PREV, { patient: 'Leak Example' })));
await no('cannot backdate updatedAt', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { updatedAt: Timestamp.fromMillis(1) }), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot backdate history', caseWrite(db, 'c1', caseUpd('gwen', 'gwen'), histDoc('gwen', 'gwen', 'c1', 4, PREV, { at: Timestamp.fromMillis(1) })));
await no('cannot change createdAt', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { createdAt: Timestamp.fromMillis(5) }), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot mark done without a close time', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { status: 'done' }), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await no('cannot use an unknown status', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { status: 'archived' }), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await ok('updates a case with its history entry', caseWrite(db, 'c1', caseUpd('gwen', 'gwen'), histDoc('gwen', 'gwen', 'c1', 4, PREV)));
await ok('marks done with a close time', caseWrite(db, 'c1', caseUpd('gwen', 'gwen', { rev: 5, status: 'done', closedAt: serverTimestamp() }), histDoc('gwen', 'gwen', 'c1', 5, PREV)));
await no('cannot delete a case (even with history)', caseWrite(db, 'c1', null, histDoc('gwen', 'gwen', 'c1', 6, PREV), 'delete'));
await no('cannot create a case without history', setDoc(doc(db, 'cases/c2'), caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp() })));
await ok('creates a case with its first history entry', caseWrite(db, 'c2', caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp() }), histDoc('gwen', 'gwen', 'c2', 1, null), 'create'));
await no('cannot create with a fake createdAt', caseWrite(db, 'c3', caseUpd('gwen', 'gwen', { rev: 1, createdAt: Timestamp.fromMillis(5) }), histDoc('gwen', 'gwen', 'c3', 1, null), 'create'));
await no('first history entry cannot claim a previous copy', caseWrite(db, 'c4', caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp() }), histDoc('gwen', 'gwen', 'c4', 1, PREV), 'create'));
await no('history id must match case and revision', (async () => { const b = writeBatch(db); b.set(doc(db, 'cases/c5'), caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp() })); b.set(doc(db, 'log/c5_1'), histDoc('gwen', 'gwen', 'c5', 1, null)); b.set(doc(db, 'log/zzz'), histDoc('gwen', 'gwen', 'c5', 1, null)); return b.commit(); })());
await no('cannot edit history', updateDoc(doc(db, 'log/c1_3'), { ct: 'eA==' }));
await no('cannot delete history', deleteDoc(doc(db, 'log/c1_3')));

console.log('\n# The patient index (4 Oct 2026): keyed hashes of name and chart # on each case');
const PN = 'p'.repeat(22), PC = 'q'.repeat(22), SAVED = { v: 2, ...box };
const save8 = (rev, extra, hextra) => { const d = caseUpd('gwen', 'gwen', Object.assign({ rev }, extra)); delete d.createdAt; return caseWrite(db, 'c8', d, histDoc('gwen', 'gwen', 'c8', rev, SAVED, hextra)); };
await ok('reads which rules are live', getDoc(doc(db, 'meta/rules_20261004')));
await ok('a new case carries its index', caseWrite(db, 'c8', caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp(), pn: PN, pc: PC }), histDoc('gwen', 'gwen', 'c8', 1, null), 'create'));
await ok('a save updates it (a new name, the chart # taken off)', save8(2, { pn: 'r'.repeat(22), pc: deleteField() }));
await no('the index can’t hold a name (wrong length)', caseWrite(db, 'c9', caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp(), pn: 'Leak Example' }), histDoc('gwen', 'gwen', 'c9', 1, null), 'create'));
await no('…or anything but text', caseWrite(db, 'c9', caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp(), pc: 12345 }), histDoc('gwen', 'gwen', 'c9', 1, null), 'create'));
await no('a history entry can’t be marked as a delete when the case stays', save8(3, {}, { del: true }));
await ok('(the same save, unmarked, goes through)', save8(3, {}));
await ok('the index alone is set without a new version (indexing the office)', updateDoc(doc(db, 'cases/c1'), { pn: PN, pc: PC }));
await ok('…and taken off', updateDoc(doc(db, 'cases/c1'), { pc: deleteField() }));
await ok('…naming the revision it was worked out from (unchanged)', updateDoc(doc(db, 'cases/c1'), { pn: PN, rev: 5 }));
await no('…not when that revision is out of date (a save came in between)', updateDoc(doc(db, 'cases/c1'), { pn: PN, rev: 4 }));
await no('an index-only write can’t change the case itself', updateDoc(doc(db, 'cases/c1'), { pn: PN, ct: 'eA==' }));
await no('…or add plaintext', updateDoc(doc(db, 'cases/c1'), { pn: PN, patient: 'Leak Example' }));
await no('…or a malformed index', updateDoc(doc(db, 'cases/c1'), { pn: 'short' }));
await no('a removed person can’t set the index', updateDoc(doc(env.authenticatedContext('kay').firestore(), 'cases/c1'), { pn: 's'.repeat(22) }));
await no('a stranger can’t set the index', updateDoc(doc(env.authenticatedContext('stranger').firestore(), 'cases/c1'), { pn: 's'.repeat(22) }));
await no('a stranger can’t read which rules are live', getDoc(doc(env.authenticatedContext('stranger').firestore(), 'meta/rules_20261004')));

console.log('\n# Owner');
db = env.authenticatedContext('owner').firestore();
await ok('lists member records', getDocs(collection(db, 'members')));
await ok('reads the recovery record', getDoc(doc(db, 'meta/recovery')));
await ok('creates a staff login', setDoc(doc(db, 'members/newbie'), { staffId: 'newbie', role: 'staff', active: true, mustSetup: true }));
await no('cannot create a second owner', setDoc(doc(db, 'members/owner2'), { staffId: 'o2', role: 'owner', active: true }));
await ok('removes a person', updateDoc(doc(db, 'members/gwen'), { active: false }));
await no('cannot demote themself', updateDoc(doc(db, 'members/owner'), { role: 'staff' }));
await no('cannot deactivate themself', updateDoc(doc(db, 'members/owner'), { active: false }));
await no('cannot delete member records (kept for history)', deleteDoc(doc(db, 'members/kay')));
await ok('bumps the key version by one', updateDoc(doc(db, 'meta/keys'), { current: 3 }));
await no('cannot skip key versions', updateDoc(doc(db, 'meta/keys'), { current: 5 }));
await no('cannot move the key version back', updateDoc(doc(db, 'meta/keys'), { current: 2 }));
await no('cannot delete a case without keeping its last copy', deleteDoc(doc(db, 'cases/c2')));
await ok('deletes a case, keeping its last copy in history', caseWrite(db, 'c2', null, histDoc('owner', 'amir', 'c2', 2, PREV), 'delete'));
await no('a delete’s mark is only ever “true”', caseWrite(db, 'c8', null, histDoc('owner', 'amir', 'c8', 4, { v: 2, ...box }, { del: 'yes' }), 'delete'));
await ok('deletes a case with its history entry marked as a delete (Deleted cases reads only those)', caseWrite(db, 'c8', null, histDoc('owner', 'amir', 'c8', 4, { v: 2, ...box }, { del: true }), 'delete'));
await ok('lists the marked deletes', getDocs(query(collection(db, 'log'), where('del', '==', true))));
await ok('sets a username', setDoc(doc(db, 'logins/newbie'), { email: 'newbie.1@staff.example' }));
await no('cannot add extra fields to a username record', setDoc(doc(db, 'logins/newbie'), { email: 'a@b.c', note: 'x' }));
await no('cannot overwrite the office setup', setDoc(doc(db, 'meta/setup'), { owner: 'owner', at: serverTimestamp() }));
await no('cannot edit history either', updateDoc(doc(db, 'log/c1_3'), { ct: 'eA==' }));

console.log('\n# Lab-email robot and the inbox');
await seed();
const PUB = { kty: 'EC', crv: 'P-256', x: 'A'.repeat(43), y: 'B'.repeat(43) };
const MID = 'm' + 'a'.repeat(40), MID2 = 'm' + 'b'.repeat(40), BEAT = 'b' + 'c'.repeat(32);
const sealed = extra => Object.assign({ kid: 'k1', epk: PUB, iv: 'aXZpdml2aXY=', ct: 'Y3Q=', at: serverTimestamp() }, extra || {});
await env.withSecurityRulesDisabled(async c => {
  const d = c.firestore();
  await setDoc(doc(d, 'mailbots/bot'), { email: 'mailbot.x@staff.example', at: Timestamp.now() });
  await setDoc(doc(d, 'meta/inbox'), { pub: PUB, kid: 'k1', senders: ['ulabsystems.com'], at: Timestamp.now() });
  await setDoc(doc(d, 'meta/inboxKey'), { keys: { k1: { v: 2, ...box } }, cur: 'k1' });
  await setDoc(doc(d, 'meta/mailbot'), { v: 2, ...box });
  await setDoc(doc(d, 'inbox/' + MID2), { kid: 'k1', epk: PUB, iv: 'aXY=', ct: 'Y3Q=', at: Timestamp.now() });
});
db = env.authenticatedContext('bot').firestore();
await ok('robot reads the inbox key it seals to', getDoc(doc(db, 'meta/inbox')));
await ok('robot adds a sealed email to the inbox', setDoc(doc(db, 'inbox/' + MID), sealed()));
await no('robot cannot overwrite an inbox item', setDoc(doc(db, 'inbox/' + MID), sealed({ ct: 'eA==' })));
await no('robot cannot read the inbox', getDoc(doc(db, 'inbox/' + MID2)));
await no('robot cannot list the inbox', getDocs(collection(db, 'inbox')));
await no('robot cannot delete inbox items', deleteDoc(doc(db, 'inbox/' + MID2)));
await no('robot cannot add plaintext to an inbox item', setDoc(doc(db, 'inbox/m' + 'd'.repeat(40)), sealed({ patient: 'Leak Example' })));
await no('robot cannot pick its own kind of id', setDoc(doc(db, 'inbox/evil'), sealed()));
await no('robot cannot backdate an inbox item', setDoc(doc(db, 'inbox/m' + 'e'.repeat(40)), sealed({ at: Timestamp.fromMillis(1) })));
await no('robot cannot send an oversized item', setDoc(doc(db, 'inbox/m' + 'f'.repeat(40)), sealed({ ct: 'x'.repeat(400001) })));
await no('robot cannot read cases', getDocs(collection(db, 'cases')));
await no('robot cannot read history', getDocs(collection(db, 'log')));
await no('robot cannot read members', getDoc(doc(db, 'members/gwen')));
await no('robot cannot read the roster', getDocs(collection(db, 'roster')));
await no('robot cannot read the office key version', getDoc(doc(db, 'meta/keys')));
await no('robot cannot read the sealed inbox private key', getDoc(doc(db, 'meta/inboxKey')));
await no('robot cannot read its own sealed login', getDoc(doc(db, 'meta/mailbot')));
await no('robot cannot swap the inbox key', setDoc(doc(db, 'meta/inbox'), { pub: PUB, kid: 'evil', senders: [], at: serverTimestamp() }));
await no('robot cannot write a case', caseWrite(db, 'x', caseUpd('bot', 'x', { rev: 1, createdAt: serverTimestamp() }), histDoc('bot', 'x', 'x', 1, null), 'create'));
await no('robot cannot make another robot', setDoc(doc(db, 'mailbots/bot2'), { email: 'x', at: serverTimestamp() }));
await ok('robot notes when it checked the mail', setDoc(doc(db, 'mailbeat/' + BEAT), { box: 'office@example.com', seen: 3, sent: 2, err: '', ver: '1', at: serverTimestamp() }));
await ok('robot updates that note', setDoc(doc(db, 'mailbeat/' + BEAT), { box: 'office@example.com', seen: 0, sent: 0, err: '', ver: '1', at: serverTimestamp() }));
await no('robot cannot put anything else in that note', setDoc(doc(db, 'mailbeat/' + BEAT), { box: 'x', seen: 0, sent: 0, err: '', ver: '1', at: serverTimestamp(), patient: 'Leak Example' }));
db = env.authenticatedContext('stranger').firestore();
await no('a stranger cannot add to the inbox', setDoc(doc(db, 'inbox/m' + '1'.repeat(40)), sealed()));
await no('a stranger cannot read the inbox key', getDoc(doc(db, 'meta/inbox')));
await no('a stranger cannot note a mail check', setDoc(doc(db, 'mailbeat/b' + '1'.repeat(32)), { box: 'x', seen: 0, sent: 0, err: '', ver: '1', at: serverTimestamp() }));
db = env.authenticatedContext('gwen').firestore();
await ok('staff read the inbox', getDocs(collection(db, 'inbox')));
await ok('staff read the inbox key and its sealed private half', Promise.all([getDoc(doc(db, 'meta/inbox')), getDoc(doc(db, 'meta/inboxKey'))]));
await ok('staff mark updates in an email as dealt with', updateDoc(doc(db, 'inbox/' + MID2), { done: [0, 2] }));
await no('staff cannot change what an email says', updateDoc(doc(db, 'inbox/' + MID2), { ct: 'eA==' }));
await ok('staff’s app claims an email while it handles it', updateDoc(doc(db, 'inbox/' + MID2), { claim: { by: 'sess1', at: serverTimestamp() } }));
await no('a claim can’t carry anything else', updateDoc(doc(db, 'inbox/' + MID2), { claim: { by: 'sess1', at: serverTimestamp(), patient: 'Leak Example' } }));
await no('a claim can’t be backdated', updateDoc(doc(db, 'inbox/' + MID2), { claim: { by: 'sess1', at: Timestamp.fromMillis(1) } }));
await ok('after a claim, the app can still mark updates as dealt with', updateDoc(doc(db, 'inbox/' + MID2), { done: arrayUnion(1) }));
await ok('…and in the same moment renew its claim', updateDoc(doc(db, 'inbox/' + MID2), { done: arrayUnion(3), claim: { by: 'sess1', at: serverTimestamp() } }));
await no('…but not backdate the claim while marking done', updateDoc(doc(db, 'inbox/' + MID2), { done: arrayUnion(4), claim: { by: 'sess1', at: Timestamp.fromMillis(1) } }));
await no('a claim can’t be removed by marking done', updateDoc(doc(db, 'inbox/' + MID2), { done: arrayUnion(5), claim: deleteField() }));
await no('staff cannot add to the inbox (only the robot can)', setDoc(doc(db, 'inbox/m' + '2'.repeat(40)), sealed()));
await ok('staff remove an email once it is dealt with', deleteDoc(doc(db, 'inbox/' + MID2)));
await ok('staff see when the mail was checked', getDocs(collection(db, 'mailbeat')));
await no('staff cannot read the robot’s login', getDoc(doc(db, 'meta/mailbot')));
await no('staff cannot make a robot login', setDoc(doc(db, 'mailbots/gwen'), { email: 'x', at: serverTimestamp() }));
await no('staff cannot change the inbox key', setDoc(doc(db, 'meta/inbox'), { pub: PUB, kid: 'k9', senders: [], at: serverTimestamp() }));
await no('a removed person cannot read the inbox', getDocs(collection(env.authenticatedContext('kay').firestore(), 'inbox')));
db = env.authenticatedContext('owner').firestore();
await ok('owner sets the inbox key', setDoc(doc(db, 'meta/inbox'), { pub: PUB, kid: 'k2', senders: ['ulabsystems.com', 'olivortho.com'], at: serverTimestamp() }));
await no('owner cannot store a malformed inbox key', setDoc(doc(db, 'meta/inbox'), { pub: { kty: 'EC', crv: 'P-256', x: 'short', y: 'short' }, kid: 'k3', senders: [], at: serverTimestamp() }));
await ok('owner seals the inbox private key', setDoc(doc(db, 'meta/inboxKey'), { keys: { k2: { v: 2, ...box } }, cur: 'k2' }));
await ok('owner keeps the robot’s sealed login', setDoc(doc(db, 'meta/mailbot'), { v: 2, ...box }));
await ok('owner makes a robot login', setDoc(doc(db, 'mailbots/bot2'), { email: 'mailbot.y@staff.example', at: serverTimestamp() }));
await ok('owner lists robot logins', getDocs(collection(db, 'mailbots')));
await ok('owner turns a robot off', deleteDoc(doc(db, 'mailbots/bot')));
db = env.authenticatedContext('bot').firestore();
await no('a robot that was turned off can’t add to the inbox', setDoc(doc(db, 'inbox/m' + '3'.repeat(40)), sealed()));
await no('…or read the inbox key', getDoc(doc(db, 'meta/inbox')));

console.log('\n# A note for the front desk: a case not shipped in time (8 Oct 2026)');
await seed();
const OID = 'o' + '1'.repeat(32), OID2 = 'o' + '2'.repeat(32), NBOX = 'b' + 'c'.repeat(32);
const NPUB = { kty: 'EC', crv: 'P-256', x: 'C'.repeat(43), y: 'D'.repeat(43) };
const note = extra => Object.assign({ box: NBOX, epk: NPUB, iv: 'aXZpdml2aXY=', ct: 'Y3Q=', at: serverTimestamp() }, extra || {});
const FD = 'Questions@thenextlevelorthodontics.com';
await env.withSecurityRulesDisabled(async c => {
  const d = c.firestore();
  await setDoc(doc(d, 'mailbots/bot'), { email: 'mailbot.x@staff.example', at: Timestamp.now() });
  await setDoc(doc(d, 'meta/inbox'), { pub: NPUB, kid: 'k1', senders: ['ulabsystems.com'], at: Timestamp.now() });
  await setDoc(doc(d, 'outbox/' + OID2), { box: NBOX, epk: NPUB, iv: 'aXY=', ct: 'Y3Q=', at: Timestamp.now() });
});
db = env.authenticatedContext('gwen').firestore();
await ok('staff’s app leaves a sealed note for the front desk', setDoc(doc(db, 'outbox/' + OID), note()));
{ // the way the app does it: in the same save as the case (and its history entry)
  const b = writeBatch(db);
  b.update(doc(db, 'cases/c1'), caseUpd('gwen', 'gwen')); b.set(doc(db, 'log/c1_4'), histDoc('gwen', 'gwen', 'c1', 4, PREV)); b.set(doc(db, 'outbox/o' + 'a'.repeat(32)), note());
  await ok('…in the same save as the case that it’s about', b.commit());
}
await no('…not with anything readable in it', setDoc(doc(db, 'outbox/o' + '3'.repeat(32)), note({ patient: 'Leak Example' })));
await no('…not under a name of its own', setDoc(doc(db, 'outbox/evil'), note()));
await no('…not addressed to something that isn’t a mailbox’s id', setDoc(doc(db, 'outbox/o' + '4'.repeat(32)), note({ box: 'office@example.com' })));
await no('…not backdated', setDoc(doc(db, 'outbox/o' + '5'.repeat(32)), note({ at: Timestamp.fromMillis(1) })));
await no('…not oversized', setDoc(doc(db, 'outbox/o' + '6'.repeat(32)), note({ ct: 'x'.repeat(20001) })));
await no('staff cannot read the notes', getDoc(doc(db, 'outbox/' + OID2)));
await no('staff cannot list the notes', getDocs(collection(db, 'outbox')));
await no('staff cannot change a note', setDoc(doc(db, 'outbox/' + OID2), note({ ct: 'eA==' })));
await no('staff cannot remove a note', deleteDoc(doc(db, 'outbox/' + OID2)));
await no('staff cannot set where the front-desk email goes', updateDoc(doc(db, 'meta/inbox'), { notify: { on: true, to: 'evil@example.com', box: NBOX, pub: NPUB, names: true } }));
await ok('staff can tell the newer rules are live', getDoc(doc(db, 'meta/rules_20261008')));
await no('a removed person cannot leave a note', setDoc(doc(env.authenticatedContext('kay').firestore(), 'outbox/o' + '7'.repeat(32)), note()));
db = env.authenticatedContext('bot').firestore();
await ok('the email robot lists the notes', getDocs(collection(db, 'outbox')));
await ok('…reads one', getDoc(doc(db, 'outbox/' + OID2)));
await ok('…and removes it once it’s sent', deleteDoc(doc(db, 'outbox/' + OID2)));
await no('the robot cannot leave a note itself', setDoc(doc(db, 'outbox/o' + '8'.repeat(32)), note()));
await no('the robot cannot change a note', setDoc(doc(db, 'outbox/' + OID), note({ ct: 'eA==' })));
await ok('the robot’s check-in carries its script’s public key', setDoc(doc(db, 'mailbeat/' + NBOX), { box: 'records@example.com', seen: 0, sent: 0, err: '', ver: '2', at: serverTimestamp(), pub: NPUB }));
await no('…only a well-formed key', setDoc(doc(db, 'mailbeat/' + NBOX), { box: 'records@example.com', seen: 0, sent: 0, err: '', ver: '2', at: serverTimestamp(), pub: { kty: 'EC', crv: 'P-256', x: 'short', y: 'short' } }));
await ok('…and an older script’s check-in (no key) still works', setDoc(doc(db, 'mailbeat/b' + 'e'.repeat(32)), { box: 'office@example.com', seen: 1, sent: 0, err: '', ver: '1', at: serverTimestamp() }));
await no('the robot cannot set where the front-desk email goes', updateDoc(doc(db, 'meta/inbox'), { notify: { on: true, to: 'evil@example.com', box: NBOX, pub: NPUB, names: true } }));
db = env.authenticatedContext('stranger').firestore();
await no('a stranger cannot leave a note', setDoc(doc(db, 'outbox/o' + '9'.repeat(32)), note()));
await no('a stranger cannot read the notes', getDocs(collection(db, 'outbox')));
await no('a stranger can’t tell which rules are live', getDoc(doc(db, 'meta/rules_20261008')));
db = env.authenticatedContext('owner').firestore();
await ok('owner turns the front-desk email on', updateDoc(doc(db, 'meta/inbox'), { notify: { on: true, to: FD, box: NBOX, pub: NPUB, names: true } }));
await ok('…keeps it when the sender list changes', updateDoc(doc(db, 'meta/inbox'), { senders: ['ulabsystems.com', 'olivortho.com'] }));
await ok('…and turns it off before a mailbox is picked', updateDoc(doc(db, 'meta/inbox'), { notify: { on: false, to: FD, box: '', names: false } }));
await no('…only to an email address', updateDoc(doc(db, 'meta/inbox'), { notify: { on: true, to: 'not an address', box: NBOX, pub: NPUB, names: true } }));
await no('…with nothing else in it', updateDoc(doc(db, 'meta/inbox'), { notify: { on: true, to: FD, box: NBOX, pub: NPUB, names: true, patient: 'Leak Example' } }));
await no('…with a well-formed key', updateDoc(doc(db, 'meta/inbox'), { notify: { on: true, to: FD, box: NBOX, pub: { kty: 'EC', crv: 'P-256', x: 'short', y: 'short' }, names: true } }));
await no('…and a mailbox id that is one', updateDoc(doc(db, 'meta/inbox'), { notify: { on: true, to: FD, box: 'records@example.com', pub: NPUB, names: true } }));
await no('owner cannot read the notes either', getDocs(collection(db, 'outbox')));
await ok('owner clears a note', deleteDoc(doc(db, 'outbox/' + OID)));
await ok('owner turns a robot off', deleteDoc(doc(db, 'mailbots/bot')));
await no('a robot that was turned off can’t read the notes', getDocs(collection(env.authenticatedContext('bot').firestore(), 'outbox')));

console.log('\n# Patient photos');
await seed();
const PH = (uid, extra) => Object.assign({ v: 2, iv: 'aXY=', ct: 'cGhvdG8=', pv: 'p1', at: serverTimestamp(), by: uid }, extra || {});
// a photo change goes in one batch with a save of its case (and that save's history entry), the way the app does it
function photoWrite(db, uid, sid, rev, ph, mode, caseId) {
  caseId = caseId || 'c1'; const b = writeBatch(db);
  b.update(doc(db, 'cases/' + caseId), caseUpd(uid, sid, { rev })); b.set(doc(db, 'log/' + caseId + '_' + rev), histDoc(uid, sid, caseId, rev, PREV));
  if (mode === 'delete') b.delete(doc(db, 'photos/' + caseId)); else b.set(doc(db, 'photos/' + caseId), ph);
  return b.commit();
}
db = env.authenticatedContext('gwen').firestore();
await no('staff cannot add a photo without saving its case', setDoc(doc(db, 'photos/c1'), PH('gwen')));
await no('a photo can’t carry anything else (e.g. a name)', photoWrite(db, 'gwen', 'gwen', 4, PH('gwen', { patient: 'Leak Example' })));
await no('a photo must use the current office key', photoWrite(db, 'gwen', 'gwen', 4, PH('gwen', { v: 1 })));
await no('a photo can’t be signed as someone else', photoWrite(db, 'gwen', 'gwen', 4, PH('owner')));
await no('a photo can’t be backdated', photoWrite(db, 'gwen', 'gwen', 4, PH('gwen', { at: Timestamp.fromMillis(1) })));
await no('a photo can’t be huge', photoWrite(db, 'gwen', 'gwen', 4, PH('gwen', { ct: 'A'.repeat(90004) })));
await no('a photo needs its version id', photoWrite(db, 'gwen', 'gwen', 4, PH('gwen', { pv: '' })));
await ok('staff add a photo together with a save of its case', photoWrite(db, 'gwen', 'gwen', 4, PH('gwen')));
await ok('staff read a case’s photo', getDoc(doc(db, 'photos/c1')));
await no('staff cannot list every photo', getDocs(collection(db, 'photos')));
await ok('staff change the photo with a case save', photoWrite(db, 'gwen', 'gwen', 5, PH('gwen', { pv: 'p2' })));
await no('staff cannot swap the picture quietly (same version id, no case save)', updateDoc(doc(db, 'photos/c1'), { ct: 'b3RoZXI=', at: serverTimestamp(), by: 'gwen' }));
await no('staff cannot delete a photo without saving its case', deleteDoc(doc(db, 'photos/c1')));
await no('a photo needs a real case', setDoc(doc(db, 'photos/nope'), PH('gwen')));
await ok('staff remove the photo with a case save', photoWrite(db, 'gwen', 'gwen', 6, null, 'delete'));
await ok('a new case and its photo go in together', (async () => { const b = writeBatch(db);
  b.set(doc(db, 'cases/c7'), caseUpd('gwen', 'gwen', { rev: 1, createdAt: serverTimestamp() })); b.set(doc(db, 'log/c7_1'), histDoc('gwen', 'gwen', 'c7', 1, null)); b.set(doc(db, 'photos/c7'), PH('gwen'));
  return b.commit(); })());
db = env.authenticatedContext('kay').firestore();
await no('a removed person cannot read photos', getDoc(doc(db, 'photos/c7')));
await no('a removed person cannot add a photo', photoWrite(db, 'kay', 'kaylee', 7, PH('kay')));
await no('a stranger cannot read photos', getDoc(doc(env.authenticatedContext('stranger').firestore(), 'photos/c7')));
await no('a signed-out visitor cannot read photos', getDoc(doc(env.unauthenticatedContext().firestore(), 'photos/c7')));
db = env.authenticatedContext('owner').firestore();
await ok('owner lists photos (to re-seal them after a key change)', getDocs(collection(db, 'photos')));
await ok('owner changes the office key', updateDoc(doc(db, 'meta/keys'), { current: 3 }));
await no('owner cannot re-seal under the old key', updateDoc(doc(db, 'photos/c7'), { v: 2, iv: 'bmV3', ct: 'bmV3', at: serverTimestamp(), by: 'owner' }));
await ok('owner re-seals a photo unchanged under the new key', updateDoc(doc(db, 'photos/c7'), { v: 3, iv: 'bmV3', ct: 'bmV3', at: serverTimestamp(), by: 'owner' }));
await no('…but not as a new picture without a case save', updateDoc(doc(db, 'photos/c7'), { v: 3, iv: 'bmV3', ct: 'bmV3', pv: 'p9', at: serverTimestamp(), by: 'owner' }));
await ok('a deleted case takes its photo with it', (async () => { const b = writeBatch(db);
  b.delete(doc(db, 'cases/c7')); b.set(doc(db, 'log/c7_2'), histDoc('owner', 'amir', 'c7', 2, { v: 2, ...box })); b.delete(doc(db, 'photos/c7'));
  return b.commit(); })());
await env.withSecurityRulesDisabled(async c => { await setDoc(doc(c.firestore(), 'photos/gone'), { v: 2, ...box, pv: 'p1', at: Timestamp.now(), by: 'owner' }); });
await ok('a photo left without its case can be cleared away', deleteDoc(doc(env.authenticatedContext('gwen').firestore(), 'photos/gone')));

console.log('\n# First-time office setup');
await env.clearFirestore();
const OWNER = { email: 'dr.test@example.com', email_verified: true };
const setupBatch = (uid, tok) => {
  const d = env.authenticatedContext(uid, tok || OWNER).firestore(); const b = writeBatch(d);
  b.set(doc(d, 'members/' + uid), { staffId: 'amir', role: 'owner', active: true });
  b.set(doc(d, 'meta/setup'), { owner: uid, at: serverTimestamp() });
  b.set(doc(d, 'meta/keys'), { current: 1 });
  b.set(doc(d, 'meta/settings'), { idleMin: 10 });
  b.set(doc(d, 'meta/recovery'), { pub: {}, priv: box, ring: box, ringV: 1 });
  b.set(doc(d, 'roster/amir'), { name: 'Amir', active: true });
  return b.commit();
};
{
  const d = env.authenticatedContext('first', OWNER).firestore();
  await no('setup record alone is refused', setDoc(doc(d, 'meta/setup'), { owner: 'first', at: serverTimestamp() }));
  await no('owner record alone is refused', setDoc(doc(d, 'members/first'), { staffId: 'a', role: 'owner', active: true }));
  const b = writeBatch(d);
  b.set(doc(d, 'members/first'), { staffId: 'a', role: 'owner', active: true });
  b.set(doc(d, 'meta/setup'), { owner: 'someoneElse', at: serverTimestamp() });
  await no('cannot name someone else as owner', b.commit());
}
await no('a stranger cannot claim the empty office', setupBatch('stranger', { email: 'attacker@example.com', email_verified: true }));
await no('the owner email alone is not enough without verifying it', setupBatch('squatter', { email: 'dr.test@example.com', email_verified: false }));
await ok('the owner (verified email) sets up the office', setupBatch('first'));
await no('a second setup is refused', setupBatch('second'));
await no('a setup claiming key version 5 is refused', (async () => {
  await env.clearFirestore();
  const d = env.authenticatedContext('third', OWNER).firestore(); const b = writeBatch(d);
  b.set(doc(d, 'members/third'), { staffId: 'a', role: 'owner', active: true });
  b.set(doc(d, 'meta/setup'), { owner: 'third', at: serverTimestamp() });
  b.set(doc(d, 'meta/keys'), { current: 5 });
  return b.commit();
})());

console.log('\nPASS ' + pass + '  FAIL ' + fail);
await env.cleanup();
process.exit(fail ? 1 : 0);
