// Retainers: made, then the front desk, then Picked up (Amir, 6 Oct 2026: "retainers are NOT placed on Sarah's desk. They are made and put
// on the front desk. the last step should be "picked up" and a note should pop up autogenerated for pt's chart saying patient picked up
// retainers and/ or whitening.. they can close it or copy it note for the chart"). Demo, made-up patients.
const { chromium } = require('playwright');
const { routes, watch } = require('./helpers');
const OUT = process.argv[2] || 'shots';
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const errs = [];
  const ctx = await browser.newContext({ viewport: { width: 1360, height: 950 } }); await routes(ctx);
  await ctx.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://127.0.0.1:8765' });
  const p = await ctx.newPage(); watch(p, errs, 'demo');
  await p.goto('http://127.0.0.1:8765/nlo-cases.html?demo'); await p.click('#lgBtn'); await p.waitForSelector('.tiles');
  let fails = 0; const check = (ok, what) => { console.log((ok ? '  ok   ' : '  FAIL ') + what); if (!ok) fails++; };
  const st = id => p.evaluate(id => { const d = DEMO.cases.get(id); return d.status + ' ' + d.stage; }, id);
  const setCase = (id, o) => p.evaluate(([id, o]) => { Object.assign(DEMO.cases.get(id), JSON.parse(JSON.stringify(o))); DEMO.emit(DEMO.cases.get(id)); }, [id, o]);

  console.log('\n# The steps: To make → Milestones → Front desk pickup → Picked up');
  check(await p.evaluate(() => FLOWS.retainer.stages.map(s => s[1]).join(' → ')) === 'To make → Milestones → Front desk pickup → Picked up', 'no Sarah’s desk; Picked up is the last step');
  const ret = await p.evaluate(() => openCases().find(c => c.type === 'retainer' && c.stage === 'pickup').id);
  // a case saved at the old step shows at Front desk pickup (where made retainers wait now)
  const old = await p.evaluate(() => openCases().find(c => c.type === 'retainer' && c.stage === 'milestones').id);
  await setCase(old, { stage: 'sarah' }); await p.waitForTimeout(150);
  check(await p.evaluate(id => findCase(id).stage, old) === 'pickup' && await p.evaluate(id => stageLabel(findCase(id)), old) === 'Front desk pickup', 'a case saved On Sarah’s desk shows at Front desk pickup');
  await p.click('#nav-board'); await p.click('[data-act=flow][data-k=retainer]'); await p.waitForSelector('.board');
  const cols = await p.$$eval('.board section.col', s => s.map(x => x.getAttribute('aria-label')));
  check(cols.join(' | ') === 'To make | Milestones | Front desk pickup', 'the board: To make, Milestones, Front desk pickup (Picked up cases are complete, so no empty column) — ' + cols.join(' | '));
  const tip = await p.getAttribute('.kc[data-id="' + ret + '"] .adv', 'title');
  check(tip === 'Move to Picked up', 'a card at Front desk pickup: the arrow says “Move to Picked up” (' + tip + ')');
  await p.screenshot({ path: OUT + '/v52-board.png' });

  console.log('\n# Picked up: the case is complete, and the note for the chart pops up');
  const pt = await p.evaluate(id => findCase(id).patient, ret);
  await p.click('.kc[data-id="' + ret + '"] .adv'); await p.waitForSelector('#puNote', { timeout: 5000 }).catch(() => {});
  const m = await p.evaluate(() => ({ h: (document.querySelector('#modalWrap h3') || {}).textContent, note: (document.querySelector('#puNote') || {}).textContent || '',
    btns: Array.from(document.querySelectorAll('#modalWrap .mFt button')).map(b => b.textContent.trim()) }));
  const L = m.note.split('\n');
  check(m.h === pt + ' picked up' && L[0] === 'Pt picked up retainers and whitening trays (U/L).', 'the note: “' + L[0] + '”');
  check(/^Reviewed retainer care with pt/.test(L[1]) && /^Reviewed whitening tray use with pt/.test(L[2]) && L.length === 3, 'then what the patient was told for retainers and whitening trays (Team & security → Chart note)');
  check(m.btns.join(' | ') === 'Close | Copy note', 'Close or Copy note');
  await p.waitForTimeout(150);
  check(await st(ret) === 'done pickedup' && !(await p.$('.kc[data-id="' + ret + '"]')), 'the case is complete, at Picked up, and off the board');
  await p.screenshot({ path: OUT + '/v52-note.png' });
  await p.click('#puCopy'); await p.waitForTimeout(150);
  const clip = await p.evaluate(() => navigator.clipboard.readText());
  check(clip === m.note && !(await p.$('#modalWrap')) && await p.isVisible('.toast:has-text("Chart note copied")'), 'Copy note: copied (the whole note), and the window closes');
  await p.click('.toast:has-text("picked up — case complete") button'); await p.waitForTimeout(300);
  check(await st(ret) === 'open pickup' && !!(await p.$('.kc[data-id="' + ret + '"]')), 'Undo: open again, back at Front desk pickup');

  console.log('\n# From the case panel, and from Edit');
  await p.evaluate(id => openDrawer(id), ret); await p.waitForSelector('#drawer .ds[data-ds=stage]');
  if (!(await p.evaluate(() => document.querySelector('#drawer .ds[data-ds=stage]').classList.contains('open')))) await p.click('#drawer .ds[data-ds=stage] .dsTg');
  await p.click('#drawer .step[data-k=pickedup]'); await p.waitForSelector('#puNote', { timeout: 5000 }).catch(() => {});
  check(!!(await p.$('#puNote')) && !(await p.isVisible('#drawer')) && await st(ret) === 'done pickedup', 'the Picked up step in its panel: the note, the case complete (the panel closes)');
  await p.click('#modalWrap [data-act=closeModal]'); await p.waitForTimeout(100);
  check(!(await p.$('#modalWrap')) && await st(ret) === 'done pickedup', 'Close: just closes (still complete)');
  // the completed case: its chart note opens on Picked up
  await p.evaluate(() => { S.closedLoaded = false; }); await p.click('#nav-done'); await p.waitForSelector('tr[data-id="' + ret + '"]');
  await p.click('tr[data-id="' + ret + '"]'); await p.waitForSelector('#drawer .ds[data-ds=note]');
  const sumTxt = (await p.textContent('#dsS-note')).trim();
  check(/^Picked up/.test(sumTxt), 'the completed case’s Chart note opens on Picked up (' + sumTxt + ')');
  await p.evaluate(() => closeDrawer(true));
  // Edit → Picked up → Save
  const mg = await p.evaluate(() => openCases().find(c => c.type === 'mouthguard').id);
  await p.evaluate(id => openDrawer(id), mg); await p.click('#drawer [data-act=edit]'); await p.waitForSelector('#drawer #cf-stage', { state: 'attached' });
  await p.selectOption('#drawer #cf-stage', 'pickedup'); await p.click('#drawer [data-act=saveEdit]');
  await p.waitForSelector('#puNote', { timeout: 5000 }).catch(() => {});
  const mgNote = await p.evaluate(() => (document.querySelector('#puNote') || {}).textContent || '');
  check(/^Pt picked up mouthguard( \((U|L|U\/L)\))?\.\nReviewed mouthguard use and care/.test(mgNote) && await st(mg) === 'done pickedup', 'a mouthguard, via Edit: “' + mgNote.split('\n')[0] + '”, complete');
  await p.click('#modalWrap [data-act=closeModal]');
  check(await p.evaluate(() => chartNote({ id: 'm', type: 'mouthguard', stage: 'pickedup', status: 'done', arches: ['Upper'] }, 'del').split('\n')[0]) === 'Pt picked up mouthguard (U).', 'with its arch when it has one: “Pt picked up mouthguard (U).”');

  console.log('\n# What the note says');
  const notes = await p.evaluate(() => {
    const n = o => chartNote(Object.assign({ id: 'x', type: 'retainer', stage: 'pickup', status: 'open', arches: ['Upper', 'Lower'], retKinds: ['TT’s'] }, o), 'del').split('\n')[0];
    return [n({}), n({ retKinds: ['WT’s'] }), n({ arches: ['Upper'], retKinds: ['TT’s', 'WT’s'] }), n({ remake: 'model' }), n({ arches: [], retKinds: [] })];
  });
  check(JSON.stringify(notes) === JSON.stringify(['Pt picked up retainers (U/L).', 'Pt picked up whitening trays (U/L).', 'Pt picked up retainers and whitening trays (U).', 'Pt picked up retainers (U/L) - remake.', 'Pt picked up retainers.']),
    'retainers, whitening trays, both, upper only, a remake, an older case with nothing picked (' + notes.join(' / ') + ')');
  check(await p.evaluate(() => chartNote(openCases().find(c => c.type === 'oliv'), 'del').startsWith('Delivered ')), 'other cases keep their delivery note');

  console.log('\n# Phone');
  await p.setViewportSize({ width: 390, height: 844 });
  const r2 = await p.evaluate(() => openCases().find(c => c.type === 'retainer' && c.stage === 'pickup').id);
  await p.evaluate(id => moveStage(id, 'pickedup'), r2); await p.waitForSelector('#puNote', { timeout: 5000 }).catch(() => {});
  const ph = await p.evaluate(() => { const md = document.querySelector('#modalWrap .modal').getBoundingClientRect(); return { fits: md.right <= innerWidth && md.left >= 0, over: document.documentElement.scrollWidth - innerWidth, copy: !!document.querySelector('#puCopy').offsetParent }; });
  check(ph.fits && ph.over <= 0 && ph.copy, 'phone: the note window fits, Copy note in reach');
  await p.screenshot({ path: OUT + '/v52-phone.png' });

  const bad = errs.filter(e => !/Failed to load resource/.test(e));
  console.log(fails ? 'FAILURES' : 'ALL OK'); console.log('ERRORS: ' + (bad.length ? bad.join('\n') : 'none'));
  await browser.close(); process.exit(fails || bad.length ? 1 : 0);
})().catch(e => { console.error('CRASH', e); process.exit(2); });
