// Builds the vault page: one HTML file with the script and styles inline, fonts and logo embedded, and a strict
// security policy that allows only this exact script and stylesheet (by hash), only Google's sign-in and database
// addresses, and no framing. Also writes the Firestore rules (with the owner's email) and the hosting config.
//   node build.mjs           -> dist/public/ (+ dist/firestore.rules, firebase.json)   needs OWNER_EMAIL=… for the rules
//   node build.mjs --emu     -> dist-test/public/ (talks to the local Firebase emulators; for the tests)
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'fs';
import { createHash } from 'crypto';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const EMU = process.argv.includes('--emu');
const ROOT = new URL('.', import.meta.url).pathname;
const OUT = ROOT + (EMU ? 'dist-test/public/' : 'dist/public/');
const DIST = ROOT + (EMU ? 'dist-test/' : 'dist/');
mkdirSync(OUT, { recursive: true });

const cfg = JSON.parse(readFileSync(ROOT + 'vault.config.json', 'utf8'));
const owner = String(process.env.OWNER_EMAIL || (EMU ? 'dr.test@example.com' : '')).trim().toLowerCase();

// assets: the shrunk white logo as a data: URL
const b64 = f => readFileSync(f).toString('base64');
writeFileSync(ROOT + 'src/assets.js', '/* generated by build.mjs */\nexport const LOGO = "data:image/png;base64,' + b64(ROOT + 'assets/logo-white.png') + '";\n');

const res = await build({
  entryPoints: [ROOT + 'src/main.js'], bundle: true, write: false, format: 'iife', platform: 'browser',
  target: ['es2020'], minify: true, legalComments: 'eof', charset: 'utf8', logLevel: 'warning',
  // Firebase 11: same API, ~200 KB smaller than 12 (which bundles a regex engine for features the vault doesn't use)
  alias: { firebase: 'firebase11' },
  define: { __VAULT_FB__: JSON.stringify(EMU ? {} : (cfg.firebase || {})), __VAULT_EMU__: EMU ? 'true' : 'false' }
});
let js = res.outputFiles[0].text;
if (!EMU && /127\.0\.0\.1:(9099|8080)/.test(js)) throw new Error('emulator addresses must not be in the production build');
js = js.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--');
if (/<\/script/i.test(js)) throw new Error('script must not contain </script');

let css = readFileSync(ROOT + 'src/style.css', 'utf8')
  .replace('__FONT_MONTSERRAT__', b64(require.resolve('@fontsource-variable/montserrat/files/montserrat-latin-wght-normal.woff2')))
  .replace('__FONT_OSWALD__', b64(require.resolve('@fontsource-variable/oswald/files/oswald-latin-wght-normal.woff2')));

const hash = s => "'sha256-" + createHash('sha256').update(s, 'utf8').digest('base64') + "'";
const connect = ['https://identitytoolkit.googleapis.com', 'https://securetoken.googleapis.com', 'https://firestore.googleapis.com']
  .concat(EMU ? ['http://127.0.0.1:9099', 'http://127.0.0.1:8080'] : []);
const csp = [
  "default-src 'none'",
  "script-src " + hash(js),
  "style-src " + hash(css),
  "img-src 'self' data: blob:",
  "font-src data:",
  "connect-src " + connect.join(' '),
  "manifest-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "object-src 'none'",
  "frame-src 'none'",
  "worker-src 'none'",
  "require-trusted-types-for 'script'",
  "trusted-types nlovault"
];
const cspHeader = csp.concat(["frame-ancestors 'none'"]).join('; ');
let page = readFileSync(ROOT + 'src/template.html', 'utf8');
const put = (ph, val) => { if (page.split(ph).length !== 2) throw new Error('placeholder ' + ph); page = page.replace(ph, () => val); };
put('__CSP_META__', csp.join('; '));
put('/*STYLE*/', css);
put('/*SCRIPT*/', js);
writeFileSync(OUT + 'index.html', page);
for (const f of ['favicon.png', 'apple-touch-icon.png', 'icon-192.png', 'icon-512.png']) copyFileSync(ROOT + 'assets/' + f, OUT + f);
writeFileSync(OUT + 'manifest.webmanifest', JSON.stringify({
  name: 'NLO Vault', short_name: 'Vault', start_url: './', scope: './', display: 'standalone', background_color: '#1B2F4C', theme_color: '#1B2F4C',
  icons: [{ src: 'icon-192.png', sizes: '192x192', type: 'image/png' }, { src: 'icon-512.png', sizes: '512x512', type: 'image/png' }]
}, null, 1));

// headers every response gets (Firebase Hosting in production; the test server reads the same list)
const headers = [
  { key: 'Content-Security-Policy', value: cspHeader },
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'no-referrer' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), payment=(), usb=()' },
  { key: 'Cross-Origin-Opener-Policy', value: 'same-origin' },
  { key: 'Cross-Origin-Resource-Policy', value: 'same-origin' },
  { key: 'X-Robots-Tag', value: 'noindex, nofollow' },
  { key: 'Cache-Control', value: 'no-cache' }
];
writeFileSync(DIST + 'headers.json', JSON.stringify(headers, null, 1));

// rules with the owner's email filled in
const rulesSrc = readFileSync(ROOT + 'firestore.rules', 'utf8');
if (rulesSrc.split('__OWNER_EMAIL__').length !== 2) throw new Error('rules placeholder');
if (owner) writeFileSync(DIST + 'firestore.rules', rulesSrc.replace('__OWNER_EMAIL__', owner));
else if (!EMU) console.log('(rules not built: run with OWNER_EMAIL=<Dr. A’s email> to make dist/firestore.rules)');

if (!EMU) {
  writeFileSync(ROOT + 'firebase.json', JSON.stringify({
    hosting: { public: 'dist/public', ignore: ['**/.*'], cleanUrls: true, trailingSlash: false, headers: [{ source: '**', headers }] },
    firestore: { rules: 'dist/firestore.rules' },
    emulators: { auth: { port: 9099 }, firestore: { port: 8080 }, ui: { enabled: false }, singleProjectMode: true }
  }, null, 2) + '\n');
}
console.log('built', OUT + 'index.html', Math.round(page.length / 1024) + ' KB', EMU ? '(emulator build)' : '', cfg.firebase ? '' : (EMU ? '' : '(no Firebase config yet: the page says "Not connected yet")'));
