"""Turn the company logos Amir pasted (logos/<key>-source.png) into small transparent PNGs and
write src/logos.js (data: URLs, allowed by the app's CSP img-src). Run: python3 tools/logos.py"""
import base64, io, json, pathlib
import numpy as np
from PIL import Image

root = pathlib.Path(__file__).resolve().parent.parent
MAX_H, MAX_W = 84, 300   # px of the stored image (shown at about 26–30 px tall, so it stays sharp on retina screens)

def white_to_alpha(im):
    """GIMP-style colour-to-alpha against white: same look on a white plate, clean edges on any other."""
    a = np.asarray(im.convert('RGBA')).astype(np.float64) / 255.0
    rgb, al = a[..., :3], a[..., 3:]
    rgb = rgb * al + (1 - al)                          # flatten any existing transparency onto white
    alpha = np.max(1 - rgb, axis=2, keepdims=True)     # how far from white
    with np.errstate(divide='ignore', invalid='ignore'):
        col = np.where(alpha > 0, 1 - (1 - rgb) / alpha, 0)
    out = np.concatenate([np.clip(col, 0, 1), alpha], axis=2)
    return Image.fromarray((out * 255 + .5).astype(np.uint8), 'RGBA')

def trim(im, pad=2):
    al = np.asarray(im)[..., 3]
    ys, xs = np.where(al > 8)
    if not len(xs): return im
    box = (max(xs.min() - pad, 0), max(ys.min() - pad, 0), min(xs.max() + 1 + pad, im.width), min(ys.max() + 1 + pad, im.height))
    return im.crop(box)

out = {}
for src in sorted((root / 'logos').glob('*-source.*')):
    key = src.name.split('-source')[0]
    im = trim(white_to_alpha(Image.open(src)))
    s = min(MAX_H / im.height, MAX_W / im.width, 1.0)
    if s < 1: im = im.resize((max(1, round(im.width * s)), max(1, round(im.height * s))), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
    (root / 'logos' / (key + '.png')).write_bytes(buf.getvalue())
    out[key] = {'src': 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode(), 'w': im.width, 'h': im.height}
    print(key, im.size, len(buf.getvalue()), 'bytes')
js = ('/* company logos for the case-type tiles (pasted by Amir, 2 Oct 2026); generated by tools/logos.py, do not edit by hand */\n'
      'const LOGOS = ' + json.dumps(out, separators=(',', ':')) + ';\n')
(root / 'src' / 'logos.js').write_text(js)
print('src/logos.js', len(js), 'bytes')
