"""Turn the case-type pictures Amir chose (pics/<tile>-source.jpg: the whole upper arch with the appliance) into
small JPEGs for the New case tiles and write src/pics.js (data: URLs, allowed by the app's CSP img-src).
Shown on a white plate like the company logos (Amir, 2 Oct 2026: "Use 1" — the whole picture).
A picture on a dark background (DARK: Amir's appliances picture, 3 Oct 2026) is cropped to its content, its edges are
faded into black, and it fills a black plate instead (PICS[key].dark).
Run: python3 tools/pics.py"""
import base64, io, json, pathlib
import numpy as np
from PIL import Image

DARK = {'appliance'}

root = pathlib.Path(__file__).resolve().parent.parent
H = 138   # px of the stored image (shown 46 px tall, so it stays sharp on 3x screens)

out = {}
for src in sorted((root / 'pics').glob('*-source.*')):
    key = src.name.split('-source')[0]
    im = Image.open(src).convert('RGB')
    dark = key in DARK
    if dark:  # the appliances themselves (and not the glow around them), with a little room
        box = Image.eval(im.convert('L'), lambda v: 255 if v > 110 else 0).getbbox()
        pad = round(im.width * .03)
    else:
        # trim the white (and the faint reflection under the trays); the study model and the MARPE model are white themselves, so anything not pure white counts
        th = 252 if key in ('models', 'marpe') else 236
        box = Image.eval(im.convert('L'), lambda v: 255 if v < th else 0).getbbox()
        pad = round(im.width * .01)
    im = im.crop((max(box[0] - pad, 0), max(box[1] - pad, 0), min(box[2] + pad, im.width), min(box[3] + pad, im.height)))
    if dark:  # fade the edges into black so the picture melts into its black plate (no seam where the glow was cut)
        a = np.asarray(im).astype(np.float32); h, w = a.shape[:2]; f = .12 * min(w, h)
        yy, xx = np.mgrid[0:h, 0:w]
        m = np.clip(np.minimum.reduce([xx / f, (w - 1 - xx) / f, yy / f, (h - 1 - yy) / f]), 0, 1)
        m = m * m * (3 - 2 * m)  # smoothstep
        im = Image.fromarray((a * m[..., None]).round().astype(np.uint8))
    if key == 'retainer':   # a clear tray on white: deepen its grey edges a little so it reads at tile size (white stays white)
        im = Image.eval(im, lambda v: max(0, round(255 - (255 - v) * 1.55)))
    hh = 150 if dark else H  # a dark picture fills its 50 px plate
    w = round(im.width * hh / im.height)
    im = im.resize((w, hh), Image.LANCZOS)
    b = io.BytesIO(); im.save(b, 'JPEG', quality=88, optimize=True, progressive=True)
    out[key] = {'src': 'data:image/jpeg;base64,' + base64.b64encode(b.getvalue()).decode(), 'w': round(w / 3), 'h': round(hh / 3)}
    if dark: out[key]['dark'] = True
    print(key, '%dx%d' % (w, hh), len(b.getvalue()), 'bytes')

js = ('/* case-type pictures for the New case tiles (chosen by Amir, 2–3 Oct 2026); generated by tools/pics.py, do not edit by hand */\n'
      'const PICS = ' + json.dumps(out, separators=(',', ':')) + ';\n')
(root / 'src' / 'pics.js').write_text(js)
print('wrote src/pics.js', len(js), 'bytes')
