"""Turn the case-type pictures Amir chose (pics/<tile>-source.jpg: the whole upper arch with the appliance) into
small JPEGs for the New case tiles and write src/pics.js (data: URLs, allowed by the app's CSP img-src).
Shown on a white plate like the company logos (Amir, 2 Oct 2026: "Use 1" — the whole picture).
Run: python3 tools/pics.py"""
import base64, io, json, pathlib
from PIL import Image

root = pathlib.Path(__file__).resolve().parent.parent
H = 138   # px of the stored image (shown 46 px tall, so it stays sharp on 3x screens)

out = {}
for src in sorted((root / 'pics').glob('*-source.*')):
    key = src.name.split('-source')[0]
    im = Image.open(src).convert('RGB')
    box = Image.eval(im.convert('L'), lambda v: 255 if v < 236 else 0).getbbox()   # trim the white (and the faint reflection under the trays)
    pad = round(im.width * .01)
    im = im.crop((max(box[0] - pad, 0), max(box[1] - pad, 0), min(box[2] + pad, im.width), min(box[3] + pad, im.height)))
    if key == 'retainer':   # a clear tray on white: deepen its grey edges a little so it reads at tile size (white stays white)
        im = Image.eval(im, lambda v: max(0, round(255 - (255 - v) * 1.55)))
    w = round(im.width * H / im.height)
    im = im.resize((w, H), Image.LANCZOS)
    b = io.BytesIO(); im.save(b, 'JPEG', quality=88, optimize=True, progressive=True)
    out[key] = {'src': 'data:image/jpeg;base64,' + base64.b64encode(b.getvalue()).decode(), 'w': round(w / 3), 'h': round(H / 3)}
    print(key, '%dx%d' % (w, H), len(b.getvalue()), 'bytes')

js = ('/* case-type pictures for the New case tiles (chosen by Amir, 2 Oct 2026); generated by tools/pics.py, do not edit by hand */\n'
      'const PICS = ' + json.dumps(out, separators=(',', ':')) + ';\n')
(root / 'src' / 'pics.js').write_text(js)
print('wrote src/pics.js', len(js), 'bytes')
