"""Clicks through the demo (the page with ?demo: a made-up office, nothing saved) on a desktop and a phone:
the time clock (PIN, punches, wrong PINs, a new PIN, a manager stepping in), and the screens for Dr. A, a manager who
approves time off, an approved laptop at home and at the office, someone on her phone at the office and at home, the time
clock off the office network, and Dr. A's office lock settings. Then the stand-alone demo page
(dist/nlo-timeclock-demo.html, for showing it before it's live) once over. The page's pinned Firebase files are served from
test/vendor/firebasejs-10.12.2/ (npm's copies, byte-identical to Google's, so the integrity check passes).
    python3 build.py && (cd dist && python3 -m http.server 8790 &) && python3 test/demo_smoke.py"""
import asyncio, os, re, sys
from playwright.async_api import async_playwright

BASE = os.environ.get('BASE_URL', 'http://127.0.0.1:8790/')
URL = BASE + 'nlo-timeclock.html?demo'
VENDOR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'vendor', 'firebasejs-10.12.2')
SHOTS = os.environ.get('SHOTS', '')
passed = failed = 0
def check(name, cond, extra=''):
    global passed, failed
    if cond: passed += 1; print('  ok  ' + name)
    else: failed += 1; print('  FAIL ' + name + ((' :: ' + str(extra)) if extra else ''))

async def shot(pg, name):
    if SHOTS: await pg.screenshot(path=os.path.join(SHOTS, name + '.png'), full_page=True)

async def digits(pg, pin):
    for d in pin: await pg.click(f'.kKey[data-d="{d}"]')
    await pg.wait_for_function("() => !document.querySelector('.kKey[disabled]')")
    await pg.wait_for_timeout(120)

async def kiosk(pg):
    await pg.goto(URL); await pg.wait_for_selector('.demoPick')
    await pg.click('[data-act=demoKiosk]'); await pg.wait_for_selector('.kTile')

async def as_who(pg, who):
    await pg.goto(URL); await pg.wait_for_selector('.demoPick')
    await pg.click(f'[data-act=demoAs][data-who={who}]'); await pg.wait_for_selector('#view .card, #view .notice')
    await pg.wait_for_timeout(250)

async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width': 1360, 'height': 900}, accept_downloads=True)
        await ctx.route('https://www.gstatic.com/firebasejs/10.12.2/*', lambda r: r.fulfill(path=os.path.join(VENDOR, r.request.url.rsplit('/', 1)[1]), content_type='text/javascript'))
        await ctx.route(re.compile(r'https://fonts\.(googleapis|gstatic)\.com/.*'), lambda r: r.fulfill(status=200, body='', content_type='text/css'))
        pg = await ctx.new_page()
        errs = []
        pg.on('pageerror', lambda e: errs.append('pageerror: ' + str(e)))
        pg.on('console', lambda m: errs.append(m.type + ': ' + m.text) if m.type in ('error', 'warning') else None)

        print('\n# the time clock')
        await kiosk(pg)
        tiles = await pg.locator('.kTile').count()
        check('seven people on the clock (Dr. A is off it)', tiles == 7, tiles)
        check('who is in, at lunch and out shows on the tiles', await pg.locator('.kTile.in').count() == 5 and await pg.locator('.kTile.lunch').count() == 1, await pg.inner_text('.kTiles'))
        check('the clock shows Thursday afternoon', 'Thursday' in await pg.inner_text('#kDate') and (await pg.inner_text('#kTime')).startswith('2:4'))
        await shot(pg, 'k1-tiles')
        await pg.click('.kTile:has-text("Robin")'); await digits(pg, '1357')
        acts = await pg.inner_text('.kPanel')
        check('right PIN: Robin’s choices are lunch or clock out', await pg.locator('.kBig[data-kind=lunch]').count() == 1 and await pg.locator('.kBig[data-kind=out]').count() == 1)
        check('…with the overtime warning and when 40 h comes', await pg.locator('.kOt.warn').count() == 1 and re.search(r'Overtime starts at 40 h, about 5:4\d PM today', acts) is not None and 'Only a manager can approve overtime' in acts, acts)
        check('…and the week in hours and minutes', re.search(r'36 h 5\d min this workweek', acts) is not None, acts)
        await shot(pg, 'k2-acts')
        await pg.click('[data-act=kWeek]'); await pg.wait_for_selector('.kTbl')
        wk = await pg.inner_text('.kTbl')
        check('My week lists the days with punches and hours', 'Mon' in wk and 'In 7:32 AM' in wk and 'Total' in wk, wk[:200])
        await pg.click('[data-act=kActs]'); await pg.click('[data-act=kCancel]'); await pg.wait_for_selector('.kTiles')
        check('Cancel goes back to the names', await pg.locator('.kTile').count() == 7)

        await pg.click('.kTile:has-text("Casey")'); await digits(pg, '1357')
        check('Casey is at lunch: back from lunch or clock out', await pg.locator('.kBig[data-kind=back]').count() == 1 and await pg.locator('.kBig[data-kind=in]').count() == 0)
        check('…and in overtime that isn’t approved: the warning says so', await pg.locator('.kOt.bad').count() == 1 and 'in overtime without approval' in (await pg.inner_text('.kOt.bad')).lower())
        await pg.click('.kBig[data-kind=back]'); await pg.wait_for_selector('[data-act=kOtYes]')
        ask = await pg.inner_text('.kPanel')
        check('back from lunch in unapproved overtime: asked first (never refused)', 'Overtime isn’t approved' in ask and 'every hour worked has to be on the clock' in ask, ask)
        await shot(pg, 'k3-otok')
        await pg.click('[data-act=kOtYes]'); await pg.wait_for_selector('.kDoneT:has-text("Back from lunch at")')
        done = await pg.inner_text('.kDone')
        check('the punch shows the time it took', 'Back from lunch at 2:4' in done and 'Casey Park' in done, done)
        check('…with the overtime warning, to acknowledge', 'got it' in done.lower() and 'in overtime without approval' in done.lower(), done)
        await pg.click('[data-act=kDone]'); await pg.wait_for_selector('.kTiles')
        check('Casey’s tile now says In', 'In · 2:4' in await pg.inner_text('.kTile:has-text("Casey")'))

        print('\n# I forgot to punch (at the time clock)')
        await pg.click('.kTile:has-text("Taylor")'); await digits(pg, '1357')
        acts = await pg.inner_text('.kPanel')
        check('Taylor asked this morning for Wednesday’s clock-out: it’s waiting', 'Waiting for a manager: Clock out 5:10 PM, Wed' in acts and 'wasn’t recorded' not in acts, acts)
        await pg.click('.kAsked [data-act=kReqUndo]'); await pg.wait_for_timeout(300)
        acts = await pg.inner_text('.kPanel')
        check('she takes it back: Wednesday’s missing clock-out shows again', 'wasn’t recorded' in acts and await pg.locator('[data-act=kReq][data-k=out]').count() == 1, acts)
        await pg.click('[data-act=kReq][data-k=out]'); await pg.wait_for_selector('.kReq')
        check('…its button opens the form on Clock out, that Wednesday', await pg.get_attribute('[data-act=krKind][aria-pressed=true]', 'data-k') == 'out' and await pg.get_attribute('[data-act=krDay][aria-pressed=true]', 'data-day') == await pg.evaluate("TCE.addDays(TCE.dayOf(nowMs()), -1)"))
        await pg.fill('#krT1', '17:10'); await pg.click('[data-act=kReqSend]'); await pg.wait_for_selector('.kAsked')
        check('…asked again', 'Waiting for a manager: Clock out 5:10 PM' in await pg.inner_text('.kPanel'))
        await pg.click('[data-act=kCancel]'); await pg.wait_for_selector('.kTiles')
        await pg.click('.kTile:has-text("Avery")'); await digits(pg, '1357')
        check('Avery left at 1: she can clock in, or say she forgot to', await pg.locator('.kBig[data-kind=in]').count() == 1 and await pg.locator('[data-act=kReq][data-k=in]').count() == 1)
        await pg.click('[data-act=kReq][data-k=in]'); await pg.wait_for_selector('.kReq')
        await shot(pg, 'k4-forgot')
        await pg.click('[data-act=kReqSend]'); await pg.wait_for_timeout(150)
        check('the time is needed', 'Type the time.' in await pg.inner_text('.kReq .kNote'))
        await pg.fill('#krT1', '23:30'); await pg.click('[data-act=kReqSend]'); await pg.wait_for_timeout(150)
        check('…not one that hasn’t happened yet', 'hasn’t happened yet' in await pg.inner_text('.kReq .kNote'))
        await pg.fill('#krT1', '14:00'); await pg.fill('#krNote', 'Came back to help with the afternoon patients')
        await pg.click('[data-act=krKind][data-k=note]'); await pg.click('[data-act=krKind][data-k=in]')
        check('what’s typed stays when the form changes', await pg.input_value('#krT1') == '14:00' and await pg.input_value('#krNote') == 'Came back to help with the afternoon patients')
        await pg.click('[data-act=kReqSend]'); await pg.wait_for_selector('.kAsked')
        acts = await pg.inner_text('.kPanel')
        check('sent: she’s in since 2:00 PM, waiting for a manager, and can clock out', 'In since 2:00 PM (waiting for a manager)' in acts and await pg.locator('.kBig[data-kind=out]').count() == 1 and 'until then it doesn’t count' in acts, acts)
        await shot(pg, 'k5-asked')
        await pg.click('.kBig[data-kind=out]'); await pg.wait_for_selector('.kDone')
        check('she clocks out; the clock-in still waits for a manager', 'Clocked out at 2:4' in await pg.inner_text('.kDone') and 'Waiting for a manager: Clock in 2:00 PM' in await pg.inner_text('.kDone'))
        await pg.click('[data-act=kDone]'); await pg.wait_for_selector('.kTiles')

        print('\n# wrong PINs: 5 in 10 minutes')
        await pg.click('.kTile:has-text("Taylor")')
        notes = []
        for i in range(5):
            await digits(pg, '2020'); notes.append(await pg.inner_text('.kNote'))
        check('each wrong PIN says how many tries are left', notes[0] == 'Wrong PIN. 4 tries left.' and notes[3] == 'Wrong PIN. 1 try left.', notes)
        check('the fifth locks it for 10 minutes', notes[4].startswith('Too many wrong PINs. Try again at 2:5'), notes[4])
        await digits(pg, '1357')
        check('even the right PIN waits until then', (await pg.inner_text('.kNote')).startswith('Too many wrong PINs'))
        await pg.click('[data-act=kCancel]'); await pg.wait_for_selector('.kTiles')
        check('the tile says it’s locked', 'Locked until' in await pg.inner_text('.kTile:has-text("Taylor")'))

        print('\n# a new PIN')
        await pg.click('.kTile:has-text("Avery")'); await digits(pg, '1357')
        await pg.click('[data-act=kNewPin]'); await digits(pg, '1111')
        check('an easy PIN is refused', 'harder to guess' in await pg.inner_text('.kNote'))
        await digits(pg, '2468'); await digits(pg, '2486')
        check('two that don’t match start over', 'didn’t match' in await pg.inner_text('.kNote'))
        await digits(pg, '2468'); await digits(pg, '2468'); await pg.wait_for_selector('.kDone')
        check('the new PIN is saved', 'PIN changed' in await pg.inner_text('.kDone'))
        await pg.click('[data-act=kDone]'); await pg.click('.kTile:has-text("Avery")'); await digits(pg, '1357')
        check('the old one stops working', (await pg.inner_text('.kNote')).startswith('Wrong PIN'))
        await digits(pg, '2468')
        check('the new one works', await pg.locator('.kBig[data-kind=in]').count() == 1)
        await pg.click('[data-act=kCancel]')

        print('\n# a manager at the time clock')
        await pg.click('[data-act=kMgr]'); await pg.click('#kmBtn'); await pg.wait_for_selector('.navBtn')
        check('signs in and sees Now', (await pg.inner_text('.topBar h2')).lower() == 'now')
        check('the sidebar knows who', 'Dr. A' in await pg.inner_text('.whoBox'))
        row = await pg.inner_text('.issue.rq:has-text("Avery Diaz missed")')
        check('Asked to fix: Avery’s clock-in, with her note', 'Clock in 2:00 PM' in row and 'Came back to help' in row, row)
        await pg.click('.issue.rq:has-text("Avery Diaz missed") [data-act=reqOpen]:has-text("Change")'); await pg.wait_for_selector('#rqT0')
        await pg.fill('#rqT0', '14:05'); await pg.click('[data-act=reqGo][data-ok="1"]'); await pg.wait_for_selector('#modalWrap', state='detached'); await pg.wait_for_timeout(250)
        check('Dr. A changes it to 2:05 and approves', 'Approved: added to Avery’s timesheet.' in await pg.inner_text('#toasts') and await pg.locator('.issue.rq:has-text("Avery Diaz missed")').count() == 0)
        await pg.click('.navBtn[data-v=sheets]'); await pg.select_option('select[data-chg=sheetPerson]', 's_avery'); await pg.wait_for_timeout(200)
        await pg.click('.pch.fixed:has-text("In 2:05 PM")'); info = await pg.inner_text('.modal')
        check('…a correction by Dr. A, saying what she asked for', 'Added by' in info and 'Asked by Avery at the time clock for Clock in 2:00 PM' in info and 'Came back to help' in info, info)
        await pg.click('[data-act=closeM]')
        await pg.click('#side [data-act=toKiosk]'); await pg.wait_for_selector('.kTiles')
        check('Back to the time clock', await pg.locator('.kTile').count() == 7)

        print('\n# Dr. A')
        await as_who(pg, 'owner')
        now = await pg.inner_text('#view')
        check('Now: one thing to fix (Taylor’s clock-out)', 'Taylor Brooks came back from lunch at 12:30 PM on Wed' in now and 'never clocked out' in now, now[:400])
        check('…and asked to fix: Taylor’s clock-out (she asked) and Avery’s note', 'Taylor Brooks missed a punch: Clock out 5:10 PM' in now and 'Avery Diaz left a note' in now and 'Taylor asked for it' in now, now[:900])
        check('Now: Robin near overtime with the time', re.search(r'Hits 40 h at 5:4\d PM', now) is not None)
        check('Now: tomorrow-morning times aren’t shown as overtime times', 'AM' not in ''.join(re.findall(r'Hits 40 h at [^\n]*', now)), re.findall(r'Hits 40 h at [^\n]*', now))
        await shot(pg, 'm1-now')
        await pg.click('.issue [data-act=addPunch]'); await pg.wait_for_selector('#apTime')
        check('the missing punch opens as a clock-out on that day', await pg.get_attribute('#apKind button[aria-pressed=true]', 'data-k') == 'out')
        await pg.click('[data-act=addPunchGo]'); await pg.wait_for_timeout(200)
        check('a time is needed', await pg.locator('#modalWrap').count() == 1)
        await pg.fill('#apTime', '17:05'); await pg.click('[data-act=addPunchGo]'); await pg.wait_for_timeout(200)
        check('a reason is needed', await pg.locator('#modalWrap').count() == 1)
        await pg.fill('#apWhy', 'Forgot to clock out; left at 5:05'); await pg.click('[data-act=addPunchGo]'); await pg.wait_for_selector('#modalWrap', state='detached')
        await pg.wait_for_timeout(300)
        await pg.click('.issue.rq:has-text("Taylor Brooks") [data-act=reqOpen][data-no]'); await pg.wait_for_selector('#rqWhy')
        await pg.fill('#rqWhy', 'Added it by hand: 5:05 per the schedule'); await pg.click('[data-act=reqGo][data-ok="0"]'); await pg.wait_for_selector('#modalWrap', state='detached')
        check('Taylor’s request declined (fixed by hand), with a note for her', 'Declined.' in await pg.inner_text('#toasts'))
        await pg.click('.issue.rq:has-text("Avery Diaz") [data-act=reqOk]'); await pg.wait_for_timeout(300)
        check('Avery’s note marked done', 'Marked done.' in await pg.inner_text('#toasts'))
        check('nothing left to fix', await pg.locator('#view .issue').count() == 0, await pg.inner_text('#view'))

        await pg.click('.navBtn[data-v=sheets]'); await pg.wait_for_selector('.card.pw')
        await pg.select_option('select[data-chg=sheetPerson]', 's_robin'); await pg.wait_for_timeout(200)
        await pg.click('.pch:has-text("In 7:21 AM")'); await pg.click('[data-act=fixMove]')
        await pg.fill('#fmTime', '07:30'); await pg.fill('#fmWhy', 'Was told to start at 7:30'); await pg.click('[data-act=fixMoveGo]')
        await pg.wait_for_selector('#modalWrap', state='detached'); await pg.wait_for_timeout(300)
        check('changing a time keeps the original, struck through', await pg.locator('.pch.void:has-text("In 7:21 AM")').count() == 1 and await pg.locator('.pch.fixed:has-text("In 7:30 AM")').count() == 1)
        check('…and the Early flag goes away', 'Early' not in await pg.inner_text('.card.pw'))
        await pg.click('.pch.fixed:has-text("In 7:30 AM")')
        info = await pg.inner_text('.modal')
        check('a correction says who added it and why', 'Added by' in info and 'Dr. A' in info and 'Was told to start at 7:30' in info, info)
        await pg.click('[data-act=closeM]')
        await pg.click('[data-act=otEdit]'); await pg.fill('#otH', '44'); await pg.click('[data-act=otGo]'); await pg.wait_for_selector('#modalWrap', state='detached'); await pg.wait_for_timeout(200)
        check('overtime approved up to 44 h shows on the week', 'Overtime approved to 44 h' in await pg.inner_text('.card.pw'))
        await shot(pg, 'm2-sheet')

        await pg.click('.navBtn[data-v=pay]'); await pg.wait_for_selector('[data-act=payCsv]')
        async with pg.expect_download() as dl: await pg.click('[data-act=payCsv]')
        csv = open(await (await dl.value).path(), encoding='utf-8-sig').read()
        check('the payroll CSV: each person’s two-week regular and overtime hours first, and the pay type', csv.startswith('"Employee","Period start","Period end","Regular hours","Overtime hours","Total hours","Pay type"') and '"Robin Hale"' in csv and '"Salaried (hours for the record)"' in csv, csv[:300])
        pay = await pg.inner_text('table.pay')
        check('payroll: Casey’s overtime, and Quinn marked salaried', re.search(r'Casey Park\s+\d+(\.\d+)?\s+0\.5\b', pay) is not None and 'Salaried' in pay, pay[:600])
        async with pg.expect_download() as dl: await pg.click('[data-act=payCsvDays]')
        days = open(await (await dl.value).path(), encoding='utf-8-sig').read()
        check('the every-day CSV lists punches and corrections', 'Added In 7:30 AM (Dr. A: Was told to start at 7:30)' in days and 'Took out In 7:21 AM' in days, days[:300])

        await pg.click('.navBtn[data-v=people]'); await pg.wait_for_selector('[data-act=pinSet]')
        await pg.click('tr:has-text("Taylor") [data-act=pinSet]'); await pg.fill('#pinA', '1234'); await pg.click('[data-act=pinGo]')
        check('an easy PIN is refused here too', await pg.locator('#modalWrap').count() == 1)
        await pg.fill('#pinA', '5829'); await pg.click('[data-act=pinGo]'); await pg.wait_for_selector('#modalWrap', state='detached')
        check('a new PIN is saved and shown once', 'PIN saved: 5829' in await pg.inner_text('#toasts'))
        await pg.click('tr:has-text("Avery") [data-act=staffEdit]'); await pg.fill('#seCap', '26'); await pg.click('[data-act=staffGo]'); await pg.wait_for_selector('#modalWrap', state='detached'); await pg.wait_for_timeout(200)
        check('a weekly cap is saved', 'Cap 26 h' in await pg.inner_text('tr:has-text("Avery")'))

        await pg.click('.navBtn[data-v=settings]'); await pg.wait_for_selector('#stThr')
        await pg.fill('#stThr', '36, 41'); await pg.click('[data-act=setSave]'); await pg.wait_for_timeout(200)
        check('a heads-up at or past overtime is refused', 'below 40' in await pg.inner_text('#toasts'))
        await pg.fill('#stThr', '35, 38'); await pg.click('[data-act=setSave]'); await pg.wait_for_timeout(300)
        check('settings save', 'Saved.' in await pg.inner_text('#toasts'))
        await pg.fill('#stOt', '44'); await pg.click('#stShift'); await pg.evaluate('queueRender()'); await pg.wait_for_timeout(200)
        check('a change not saved yet stays on screen when live updates come in', await pg.input_value('#stOt') == '44')
        await pg.fill('#stOt', '40')

        await pg.click('.navBtn[data-v=alerts]'); await pg.wait_for_selector('#alEm')
        await pg.fill('#alEm', 'dr.a@example.com\nnot-an-email'); await pg.click('.card:has(#alEm) [data-act=alertsSave]'); await pg.wait_for_timeout(200)
        check('a bad address is refused', 'Not an email address: not-an-email' in await pg.inner_text('#toasts'))
        await pg.fill('#alEm', 'dr.a@example.com\nmanager@example.com'); await pg.click('.card:has(#alEm) [data-act=alertsSave]'); await pg.wait_for_timeout(300)
        check('two addresses saved', 'manager@example.com' in await pg.input_value('#alEm'))
        await pg.click('[data-act=getScript]'); await pg.click('#modalWrap [data-x=yes]'); await pg.wait_for_selector('[data-act=copyScript]')
        check('Get the script gives the steps', 'script.new' in await pg.inner_text('.modal'))
        await pg.click('[data-act=closeM]')
        await shot(pg, 'm3-alerts')

        print('\n# a manager who approves time off (not Dr. A)')
        await as_who(pg, 'manager')
        await pg.click('.navBtn[data-v=sheets]'); await pg.wait_for_selector('.card.pw')
        await pg.select_option('select[data-chg=sheetPerson]', 's_morgan'); await pg.wait_for_timeout(200)
        mine = await pg.inner_text('.card.pw')
        check('can’t correct their own time', 'Only Dr. A corrects your own time.' in mine and await pg.locator('.card.pw [data-act=addPunch]').count() == 0)
        await pg.select_option('select[data-chg=sheetPerson]', 's_taylor'); await pg.wait_for_timeout(200)
        check('can correct someone else’s', await pg.locator('.card.pw [data-act=addPunch]').count() == 1)
        await pg.click('.navBtn[data-v=settings]'); await pg.wait_for_selector('#stOt')
        check('settings are read-only', await pg.is_disabled('#stOt') and await pg.locator('[data-act=setSave]').count() == 0)

        print('\n# Jamie’s approved laptop (working from home)')
        async def where(page, w):
            await page.click(f'#demoBar [data-act=demoWhere][data-w={w}]'); await page.wait_for_timeout(450)
        await pg.goto(URL); await pg.wait_for_selector('.demoPick')
        check('the demo bar switches where this device is', await pg.locator('#demoBar [data-act=demoWhere]').count() == 2)
        await where(pg, 'home')
        await pg.click('[data-act=demoLaptop]'); await pg.wait_for_selector('.kTile')
        check('the laptop shows only the people it’s for (Jamie)', await pg.locator('.kTile').count() == 1 and 'jamie' in (await pg.inner_text('.kTiles')).lower() and 'approved laptop' in (await pg.inner_text('#kMain')).lower(), await pg.inner_text('#kMain'))
        check('…and its name', 'remote laptop' in (await pg.inner_text('#kName')).lower(), await pg.inner_text('#kName'))
        await pg.click('.kTile:has-text("Jamie")'); await digits(pg, '1357'); await pg.wait_for_selector('.kBig')
        acts = await pg.inner_text('.kPanel')
        check('at home: clock in and out only, marked Home', 'Away from the office: clock in and out only' in acts and await pg.locator('.kBig[data-kind=out]').count() == 1 and await pg.locator('.kBig[data-kind=lunch]').count() == 0, acts)
        await pg.click('.kBig[data-kind=out]'); await pg.wait_for_selector('.kDone')
        done = await pg.inner_text('.kDone')
        check('…she clocks out: marked Home', 'Clocked out at 2:4' in done and 'Marked Home on your timesheet' in done, done)
        await pg.click('[data-act=kDone]'); await where(pg, 'office')
        await pg.click('.kTile:has-text("Jamie")'); await digits(pg, '1357'); await pg.wait_for_selector('.kBig[data-kind=in]')
        await pg.click('.kBig[data-kind=in]'); await pg.wait_for_selector('.kDone')
        check('at the office on the laptop: an office punch (not Home)', 'Clocked in at' in await pg.inner_text('.kDone') and 'Marked Home' not in await pg.inner_text('.kDone'))
        await pg.click('[data-act=kDone]'); await pg.click('.kTile:has-text("Jamie")'); await digits(pg, '1357'); await pg.wait_for_selector('.kBig')
        check('…and everything there (out to lunch too)', await pg.locator('.kBig[data-kind=lunch]').count() == 1 and 'Away from the office' not in await pg.inner_text('.kPanel'))
        await pg.click('[data-act=kCancel]')

        print('\n# Taylor, on her phone')
        await as_who(pg, 'staff'); await pg.wait_for_selector('[data-act=ownPunch]')
        me = await pg.inner_text('#view')
        check('on the office Wi-Fi: My time has the punch buttons', await pg.locator('[data-act=ownPunch][data-kind=out]').count() == 1 and await pg.locator('[data-act=ownPunch][data-kind=lunch]').count() == 1 and 'On the office network' in me, me[:400])
        check('…and what she asked for (Wednesday’s clock-out, waiting)', 'Clock out 5:10 PM' in me and 'Waiting for a manager' in me and await pg.locator('[data-act=meReq]').count() == 1, me[:500])
        await pg.click('[data-act=ownPunch][data-kind=out]'); await pg.wait_for_selector('[data-act=ownPunch][data-kind=in]')
        check('she clocks out on her phone', 'Clocked out at 2:4' in await pg.inner_text('#toasts'))
        await where(pg, 'home'); await pg.wait_for_selector('.netAway')
        me = await pg.inner_text('#view')
        check('at home: no punch buttons, and why', await pg.locator('[data-act=ownPunch]').count() == 0 and 'You’re not on the office network' in me and 'Home Internet' in me, me[:400])
        await pg.click('[data-act=meReq]'); await pg.click('[data-act=mrKind][data-k=note]'); await pg.fill('#mrNote', 'Worked 30 min Wednesday night on insurance calls')
        await pg.click('[data-act=meReqGo]'); await pg.wait_for_selector('#modalWrap', state='detached'); await pg.wait_for_timeout(250)
        check('…but “I forgot to punch” works from anywhere', 'Worked 30 min Wednesday night' in await pg.inner_text('#view'))
        await pg.click('.rqMine:has-text("Worked 30 min") [data-act=reqUndo]'); await pg.wait_for_timeout(300)
        check('…and taken back', 'Worked 30 min Wednesday night' not in await pg.inner_text('#view'))
        check('no manager screens', await pg.locator('.navBtn[data-v=now]').count() == 0)
        await where(pg, 'office')

        print('\n# the time clock off the office network')
        await pg.goto(URL); await pg.wait_for_selector('.demoPick'); await where(pg, 'home')
        await pg.click('[data-act=demoKiosk]'); await pg.wait_for_selector('.kTile'); await pg.wait_for_selector('.kNetOff', timeout=9000)
        check('a line says it isn’t on the office network', 'isn’t on the office network' in await pg.inner_text('.kNetOff'))
        await pg.click('.kTile:has-text("Morgan")'); await digits(pg, '1357'); await pg.wait_for_selector('.kBig[data-kind=lunch]')
        await pg.click('.kBig[data-kind=lunch]'); await pg.wait_for_selector('.kDone')
        check('…the punch still goes through, flagged for a manager', 'Out to lunch at' in await pg.inner_text('.kDone') and 'flagged for a manager' in await pg.inner_text('.kDone'), await pg.inner_text('.kDone'))
        await pg.click('[data-act=kDone]'); await where(pg, 'office')

        print('\n# Dr. A: the office network and the laptops')
        await pg.click('[data-act=kMgr]'); await pg.click('#kmBtn'); await pg.wait_for_selector('#app:not(.hidden)'); await pg.wait_for_timeout(300)
        await pg.click('.navBtn[data-v=sheets]'); await pg.wait_for_selector('.card.pw')
        await pg.select_option('select[data-chg=sheetPerson]', 's_morgan'); await pg.wait_for_function("document.querySelectorAll('.card.pw').length === 1"); await pg.wait_for_timeout(200)
        sh = await pg.inner_text('#view')
        check('a time-clock punch that couldn’t check the network is flagged', 'Network not checked' in sh and 'Off the office network' in sh, sh[:600])
        await pg.select_option('select[data-chg=sheetPerson]', 's_jamie'); await pg.wait_for_function("document.querySelectorAll('.card.pw').length === 1 && document.querySelector('.card.pw h3').textContent.includes('Jamie')"); await pg.wait_for_timeout(200)
        tip = await pg.get_attribute('.card.pw .pch:has(svg) >> nth=0', 'title')
        check('Jamie’s laptop punches from home say so', 'from home (Remote laptop)' in (tip or ''), tip)
        await pg.click('.navBtn[data-v=people]'); await pg.wait_for_selector('tr:has-text("Jamie")')
        check('People: Jamie from home on the Remote laptop', 'Remote laptop' in await pg.inner_text('tr:has-text("Jamie")'))
        await pg.click('.navBtn[data-v=settings]'); await pg.wait_for_selector('#officeCard')
        oc = await pg.inner_text('#officeCard')
        check('Settings: the office lock is on, with the office’s network', 'Office Wi-Fi' in oc and 'workers.dev' in oc and await pg.locator('#officeCard [data-act=lockOff]').count() == 1, oc[:500])
        check('…and the approved laptops', 'Remote laptop' in await pg.inner_text('#view') and 'Quinn’s laptop' in await pg.inner_text('#view'))
        await pg.click('[data-act=offHere]'); await pg.wait_for_selector('#modalWrap')
        check('This is the office, at the office: already saved', 'Already saved as “Office Wi-Fi”' in await pg.inner_text('#modalWrap'))
        await pg.click('#modalWrap [data-act=closeM]')
        await where(pg, 'home'); await pg.click('.navBtn[data-v=settings]'); await pg.wait_for_selector('#officeCard')
        await pg.click('[data-act=offHere]'); await pg.wait_for_selector('#offName')
        await pg.fill('#offName', 'Second line'); await pg.click('[data-act=offHereGo]'); await pg.wait_for_selector('#modalWrap', state='detached'); await pg.wait_for_timeout(300)
        check('…saving another network', 'Second line' in await pg.inner_text('#officeCard'))
        await pg.click('#officeCard .kvRow:has-text("Second line") [data-act=offRemove]'); await pg.click('#modalWrap [data-x=yes]'); await pg.wait_for_timeout(300)
        check('…and removing it', 'Second line' not in await pg.inner_text('#officeCard'))
        await pg.click('[data-act=lockOff]'); await pg.click('#modalWrap [data-x=yes]'); await pg.wait_for_timeout(400)
        check('turning the lock off', await pg.locator('#officeCard [data-act=lockOn]').count() == 1)
        await pg.click('[data-act=lockOn]'); await pg.wait_for_timeout(700)
        check('…it turns on only from the office network', 'from a computer on the office network' in await pg.inner_text('#toasts') and await pg.locator('#officeCard [data-act=lockOn]').count() == 1)
        await where(pg, 'office'); await pg.click('.navBtn[data-v=settings]'); await pg.wait_for_selector('#officeCard')
        await pg.click('[data-act=lockOn]'); await pg.wait_for_timeout(700)
        check('…and it’s on again', await pg.locator('#officeCard [data-act=lockOff]').count() == 1)
        check('…and which kinds of address are saved (IPv4 only so far: save it from a phone too)', 'IPv4' in await pg.inner_text('#officeCard .ofCover'), oc[:600])
        lv = await pg.inner_text('#view')
        check('a laptop is asking to be approved (when; nothing it says until its code matches), with the code to type', 'asking to be approved' in lv and 'min ago' in lv and 'Chrome on Windows' not in lv and await pg.locator('#lapCode').count() == 1, lv[-900:])
        await pg.fill('#lapCode', '123456'); await pg.click('[data-act=lapFind]'); await pg.wait_for_timeout(300)
        check('…a code that isn’t the laptop’s finds nothing', 'No laptop is asking with that code' in await pg.inner_text('#toasts') and await pg.locator('#leName').count() == 0)
        await pg.fill('#lapCode', '482 913'); await pg.click('[data-act=lapFind]'); await pg.wait_for_selector('#leName')
        check('…its code opens the approval (who uses it, its name)', 'Chrome on Windows' in await pg.inner_text('#modalWrap') and await pg.locator('#modalWrap .lapWho').count() == 7)
        await pg.fill('#leName', 'Avery’s laptop'); await pg.check('.lapWho[value=s_avery]'); await pg.click('[data-act=lapApproveGo]'); await pg.wait_for_selector('#modalWrap', state='detached'); await pg.wait_for_timeout(300)
        lv = await pg.inner_text('#view')
        check('approved for Avery: it’s on the list, nothing waiting', 'Avery’s laptop' in lv and 'asking to be approved' not in lv, lv[-900:])
        check('…and Avery may now clock in from home (on it)', 'Yes' in await pg.evaluate("String(staffOf('s_avery').home ? 'Yes' : 'No')"))

        print('\n# a laptop with the office lock off (it still checks where it is)')
        await as_who(pg, 'owner'); await pg.click('.navBtn[data-v=settings]'); await pg.wait_for_selector('#officeCard [data-act=lockOff]')
        await pg.click('[data-act=lockOff]'); await pg.click('#modalWrap [data-x=yes]'); await pg.wait_for_selector('#officeCard [data-act=lockOn]')
        await pg.click('#side [data-act=signOut]'); await pg.wait_for_selector('.demoPick')
        await pg.click('[data-act=demoLaptop]'); await pg.wait_for_selector('.kTile')
        await pg.click('.kTile:has-text("Jamie")'); await digits(pg, '1357'); await pg.wait_for_selector('.kBig')
        check('lock off, at the office: everything on the laptop (out to lunch too), not Home', await pg.locator('.kBig[data-kind=lunch]').count() == 1 and 'Away from the office' not in await pg.inner_text('.kPanel'), await pg.inner_text('.kPanel'))
        await pg.click('[data-act=kCancel]'); await where(pg, 'home')
        await pg.click('.kTile:has-text("Jamie")'); await digits(pg, '1357'); await pg.wait_for_selector('.kBig')
        check('…at home: clock in and out only', await pg.locator('.kBig[data-kind=lunch]').count() == 0 and 'Away from the office' in await pg.inner_text('.kPanel'), await pg.inner_text('.kPanel'))
        await pg.click('[data-act=kCancel]'); await where(pg, 'office')

        print('\n# phones')
        ph = await b.new_context(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True)
        await ph.route('https://www.gstatic.com/firebasejs/10.12.2/*', lambda r: r.fulfill(path=os.path.join(VENDOR, r.request.url.rsplit('/', 1)[1]), content_type='text/javascript'))
        await ph.route(re.compile(r'https://fonts\.(googleapis|gstatic)\.com/.*'), lambda r: r.fulfill(status=200, body='', content_type='text/css'))
        pp = await ph.new_page(); pp.on('pageerror', lambda e: errs.append('pageerror (phone): ' + str(e)))
        await kiosk(pp)
        w = await pp.evaluate('document.documentElement.scrollWidth')
        check('the time clock fits a phone', w <= 390, w)
        await pp.tap('.kTile:has-text("Robin")'); await pp.wait_for_selector('.kPad')
        check('the PIN pad fits', await pp.evaluate('document.documentElement.scrollWidth') <= 390)
        await as_who(pp, 'staff'); await pp.wait_for_selector('[data-act=ownPunch]')
        check('My time with the punch buttons fits a phone', await pp.evaluate('document.documentElement.scrollWidth') <= 391)
        await as_who(pp, 'owner')
        for v in ['now', 'sheets', 'pay', 'people', 'alerts', 'settings']:
            await pp.evaluate(f"document.querySelector('.navBtn[data-v={v}]').click()"); await pp.wait_for_timeout(250)
            sw = await pp.evaluate('document.documentElement.scrollWidth')
            check(f'{v} has no sideways scrolling on a phone', sw <= 391, sw)
        await ph.close()

        print('\n# the stand-alone demo page')
        sp = await ctx.new_page(); sp.on('pageerror', lambda e: errs.append('pageerror (stand-alone): ' + str(e)))
        await sp.goto(BASE + 'nlo-timeclock-demo.html'); await sp.wait_for_selector('.demoPick')
        check('no Firebase on it', await sp.evaluate('typeof firebase') == 'undefined')
        await sp.click('[data-act=demoAs][data-who=owner]'); await sp.wait_for_selector('.nowRow')
        await sp.click('.navBtn[data-v=pay]'); await sp.wait_for_selector('table.pay')
        check('payroll says downloads and printing are in the office’s copy (the demo can’t download)', await sp.locator('[data-act=payCsv]').count() == 0 and 'CSV files' in await sp.inner_text('#view'))
        await sp.click('.navBtn[data-v=now]'); await sp.click('#side [data-act=signOut]'); await sp.wait_for_selector('.demoPick')
        await sp.click('[data-act=demoKiosk]'); await sp.wait_for_selector('.kTile')
        check('its time clock opens', await sp.locator('.kTile').count() == 7)

        check('no errors in the console', not errs, errs)
        await b.close()
    print(f'\n{passed} passed, {failed} failed')
    sys.exit(1 if failed else 0)

asyncio.run(main())
